Repository ethersphere/swarm, pull requests merged in 2018-02, with the labels that each got.

#247 Make swarm-network-rewrite-syncer green - 1
  internal/jsre/deps/web3.js
  log/logger.go
  log/root.go
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  p2p/simulations/adapters/inproc.go
  pot/doc.go
  pot/pot.go
  swarm/api/api_test.go
  swarm/api/http/error.go
  swarm/api/http/server.go
  swarm/api/manifest.go
  swarm/api/storage.go
  swarm/api/storage_test.go
  swarm/network/discovery_test.go
  swarm/network/kademlia.go
  swarm/network/protocol.go
  swarm/network/protocol_test.go
  swarm/network/simulations/discovery/discovery_test.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/peer.go
  swarm/network/stream/streamer_test.go
  swarm/pss/client/client_test.go
  swarm/pss/handshake.go
  swarm/pss/protocol.go
  swarm/pss/protocol_test.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/storage/dbstore.go
Labels: in progress

#256 configurable EnableMsgEvents ; enable TestDeliveryFromNodes and TestSyncerSimulation
  contracts/chequebook/cheque_test.go
  p2p/simulations/adapters/inproc.go
  p2p/simulations/adapters/types.go
  p2p/simulations/http.go
  p2p/simulations/http_test.go
  p2p/simulations/mocker.go
  p2p/simulations/network.go
  p2p/simulations/network_test.go
  swarm/network/simulations/discovery/discovery_test.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
  swarm/pss/client/client_test.go
  swarm/pss/pss_test.go
Labels: ready for review

#251 Make swarm-network-rewrite-syncer green - 2
  .travis.yml
  contracts/chequebook/cheque_test.go
  p2p/protocols/protocol_test.go
  p2p/simulations/adapters/inproc.go
  p2p/simulations/adapters/inproc_test.go
  p2p/simulations/adapters/types.go
  p2p/simulations/http.go
  p2p/simulations/http_test.go
  p2p/simulations/mocker.go
  p2p/simulations/network.go
  p2p/simulations/network_test.go
  pot/address.go
  pot/pot_test.go
  swarm/network/bitvector/bitvector.go
  swarm/network/bitvector/bitvector_test.go
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/light/lightnode.go
  swarm/network/simulations/discovery/discovery_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/stream.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
  swarm/pss/api.go
  swarm/pss/client/client_test.go
  swarm/pss/handshake.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/storage/chunker.go
  swarm/storage/dbstore.go
  swarm/storage/dbstore_test.go
  swarm/storage/resource.go
  swarm/storage/types.go
  swarm/swarm.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_go1.10.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_go1.9.go
  vendor/vendor.json
  whisper/whisperv6/peer_test.go
Labels: ready for review

#212 Add granular error reporting in mutable resources
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/network/protocol_test.go
  swarm/storage/dbstore.go
  swarm/storage/dbstore_test.go
  swarm/storage/dpa.go
  swarm/storage/error.go
  swarm/storage/memstore.go
  swarm/storage/memstore_test.go
  swarm/storage/netstore.go
  swarm/storage/resource.go
Labels: ready for another review, resource update, swarm-network-rewrite

#214 Infer multihash resource update content when datalength header is 0
  swarm/api/http/server.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  vendor/github.com/jbenet/go-base58/LICENSE
  vendor/github.com/jbenet/go-base58/README.md
  vendor/github.com/jbenet/go-base58/base58.go
  vendor/github.com/jbenet/go-base58/doc.go
  vendor/github.com/multiformats/go-multihash/LICENSE
  vendor/github.com/multiformats/go-multihash/Makefile
  vendor/github.com/multiformats/go-multihash/README.md
  vendor/github.com/multiformats/go-multihash/io.go
  vendor/github.com/multiformats/go-multihash/multihash.go
  vendor/github.com/multiformats/go-multihash/package.json
  vendor/github.com/multiformats/go-multihash/sum.go
  vendor/github.com/spaolacci/murmur3/LICENSE
  vendor/github.com/spaolacci/murmur3/README.md
  vendor/github.com/spaolacci/murmur3/murmur.go
  vendor/github.com/spaolacci/murmur3/murmur128.go
  vendor/github.com/spaolacci/murmur3/murmur32.go
  vendor/github.com/spaolacci/murmur3/murmur64.go
  vendor/golang.org/x/crypto/blake2b/blake2b.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_generic.go
  vendor/golang.org/x/crypto/blake2b/blake2b_ref.go
  vendor/golang.org/x/crypto/blake2b/register.go
  vendor/golang.org/x/crypto/blake2s/blake2s.go
  vendor/golang.org/x/crypto/blake2s/blake2s_386.go
  vendor/golang.org/x/crypto/blake2s/blake2s_386.s
  vendor/golang.org/x/crypto/blake2s/blake2s_amd64.go
  vendor/golang.org/x/crypto/blake2s/blake2s_amd64.s
  vendor/golang.org/x/crypto/blake2s/blake2s_generic.go
  vendor/golang.org/x/crypto/blake2s/blake2s_ref.go
  vendor/golang.org/x/crypto/blake2s/register.go
  vendor/golang.org/x/crypto/sha3/doc.go
  vendor/golang.org/x/crypto/sha3/hashes.go
  vendor/golang.org/x/crypto/sha3/keccakf.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.s
  vendor/golang.org/x/crypto/sha3/register.go
  vendor/golang.org/x/crypto/sha3/sha3.go
  vendor/golang.org/x/crypto/sha3/shake.go
  vendor/golang.org/x/crypto/sha3/xor.go
  vendor/golang.org/x/crypto/sha3/xor_generic.go
  vendor/golang.org/x/crypto/sha3/xor_unaligned.go
  vendor/leb.io/hashland/LICENSE
  vendor/leb.io/hashland/keccakpg/keccak.go
  vendor/vendor.json
Labels: ready for another review, resource update, swarm-network-rewrite

#268 refactor ShowError and introduce RUID for each HTTP request
  swarm/api/http/error.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
Labels: ready for review

#274 fix pyramid chunker
  swarm/storage/chunker_test.go
  swarm/storage/common_test.go
  swarm/storage/dpa_test.go
  swarm/storage/pyramid.go
Labels: ready for review

#275 Swarm network rewrite syncer intervals
  swarm/network/light/lightnode.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals/dbstore.go
  swarm/network/stream/intervals/dbstore_test.go
  swarm/network/stream/intervals/intervals.go
  swarm/network/stream/intervals/intervals_test.go
  swarm/network/stream/intervals/store.go
  swarm/network/stream/intervals/store_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/stream.go
  swarm/network/stream/streamer_test.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
  swarm/swarm.go
Labels: network rewrite
