Repository ethersphere/swarm, pull requests merged in 2018-03, with the labels that each got.

#278 Remove deprecated `swarm cleandb`
  cmd/swarm/main.go
Labels: ready for review

#334 improved tracing
  p2p/discover/table.go
  p2p/server.go
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/api/manifest.go
  swarm/storage/memstore.go
  swarm/storage/pyramid.go
Labels: ready for review

#313 Request sync stream subscriptions on Kademlia depth change
  .travis.yml
  cmd/swarm/config.go
  cmd/swarm/main.go
  swarm/api/config.go
  swarm/network/kademlia.go
  swarm/network/light/lightnode.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/stream.go
  swarm/network/stream/streamer_test.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/swarm.go
Labels: ready for review

#336 deadlock on retrieve chunk + more tracing for internal swarm components
  log/format.go
  swarm/storage/chunker.go
  swarm/storage/ldbstore.go
  swarm/storage/localstore.go
  swarm/storage/memstore.go
  swarm/storage/pyramid.go
Labels: ready for another review

#348 swarm/pss: Remove go1.7 test workaround
  swarm/pss/protocol_go18plus_test.go
  swarm/pss/protocol_test.go
  swarm/pss/pss_go18plus_test.go
Labels: pss, ready for review

#318 swarm/storage: Add max period traversal for lookup query
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/storage/error.go
  swarm/storage/ldbstore.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/swarm.go
  swarm/testutil/http.go
Labels: ready for another review, resource update

#327 Integrate encryption into dpa and chunker
  cmd/swarm/config_test.go
  cmd/swarm/hash.go
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/config.go
  swarm/api/filesystem.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/fuse/swarmfs_test.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/pss/pss.go
  swarm/storage/chunker.go
  swarm/storage/chunker_test.go
  swarm/storage/chunkstore.go
  swarm/storage/dpa.go
  swarm/storage/dpa_test.go
  swarm/storage/encryption.go
  swarm/storage/encryption/encryption.go
  swarm/storage/encryption/encryption_test.go
  swarm/storage/hasherstore.go
  swarm/storage/hasherstore_test.go
  swarm/storage/ldbstore_test.go
  swarm/storage/pyramid.go
  swarm/storage/types.go
  swarm/swarm.go
  swarm/testutil/http.go
Labels: encryption, ready for another review

#353 fix swarm db export import
  cmd/swarm/export_test.go
  cmd/swarm/run_test.go
  common/bytes.go
  swarm/storage/ldbstore.go
  swarm/swarm.go
Labels: ready for review

#349 enable TestCLISwarmUp
  cmd/swarm/upload_test.go
Labels: ready for review
