Repository ethersphere/swarm, pull requests merged in 2018-06, with the labels that each got.

#655 merge master to swarm-network-rewrite
  VERSION
  common/bytes.go
  common/math/big.go
  common/number/int.go
  common/path.go
  common/types.go
  common/types_template.go
  core/state/state_test.go
  core/state/sync.go
  core/tx_pool.go
  core/types/transaction_test.go
  core/vm/gas_table.go
  core/vm/jump_table.go
  eth/downloader/downloader.go
  eth/downloader/statesync.go
  eth/fetcher/fetcher.go
  ethstats/ethstats.go
  interfaces.go
  p2p/discv5/metrics.go
  p2p/discv5/udp.go
  params/version.go
  trie/encoding.go
  trie/sync.go
  trie/sync_test.go
  whisper/shhclient/client.go
Labels: ready for review

#660 Rename DPA to FileStore
  cmd/swarm/hash.go
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/config.go
  swarm/api/filesystem.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/fuse/swarmfs_test.go
  swarm/network/discovery.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
  swarm/pss/ARCHITECTURE.md
  swarm/pss/pss.go
  swarm/storage/chunkstore.go
  swarm/storage/filestore.go
  swarm/storage/filestore_test.go
  swarm/storage/ldbstore.go
  swarm/storage/mru/resource.go
  swarm/swarm.go
  swarm/swarm_test.go
  swarm/testutil/http.go
Labels: ready for review, storage-refactor

#662 swarm/pss: Rename "self" receivers to reflect better their identity
  swarm/pss/client/client.go
  swarm/pss/handshake.go
  swarm/pss/ping.go
  swarm/pss/protocol.go
  swarm/pss/pss.go
  swarm/pss/types.go
Labels: pss, ready for review

#664 swarm/api: fix linter error
  swarm/api/http/server.go
Labels: ready for review

#661 Pyramid split fix
  swarm/storage/chunker_test.go
  swarm/storage/pyramid.go
  swarm/swarm_test.go
Labels: ready for review

#637 swarm/pss: Pssmsg flags
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/pss/types.go
Labels: enhancement, pss, ready for another review

#669 swarm: added copyright headers
  cmd/swarm/swarm-smoke/upload_and_sync.go
  swarm/network/bitvector/bitvector.go
  swarm/network/bitvector/bitvector_test.go
  swarm/network/common.go
  swarm/network/priorityqueue/priorityqueue.go
  swarm/network/priorityqueue/priorityqueue_test.go
  swarm/network/simulations/discovery/discovery.go
  swarm/network/simulations/discovery/discovery_test.go
  swarm/pss/api.go
  swarm/pss/client/client.go
  swarm/pss/client/client_test.go
  swarm/pss/client/doc.go
  swarm/pss/doc.go
  swarm/pss/handshake.go
  swarm/pss/handshake_none.go
  swarm/pss/handshake_test.go
  swarm/pss/ping.go
  swarm/pss/protocol.go
  swarm/pss/protocol_none.go
  swarm/pss/protocol_test.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/pss/types.go
  swarm/state.go
  swarm/storage/common.go
  swarm/storage/error.go
  swarm/storage/localstore_test.go
Labels: ready for review

#674 swarm/network: scale down test - TestFileRetrieval
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/syncer_test.go
  swarm/storage/chunker_test.go
Labels: ready for review

#679 p2p, swarm: do not log shutting down as error
  p2p/peer.go
  swarm/network/stream/stream.go
Labels: ready for review

#677 swarm/network: disable TestSuggestPeerRetries
  swarm/network/kademlia_test.go
Labels: ready for review

#653 swarm/pss: add error logging ; amend timeouts
  p2p/metrics.go
  p2p/protocols/protocol.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/testutil/http.go
Labels: ready for review

#688 Log if chunk to deliver is too short
  swarm/network/stream/delivery.go
  swarm/network/stream/messages.go
Labels: ready for review

#689 Log unexpected db error in processReceivedChunks
  swarm/network/stream/delivery.go
Labels: bug, ready for review

#680 swarm: wrap logger with stats for Warn, Crit and Error
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/config.go
  swarm/api/filesystem.go
  swarm/api/http/roundtripper.go
  swarm/api/http/server.go
  swarm/api/manifest.go
  swarm/fuse/fuse_dir.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
  swarm/log/log.go
  swarm/metrics/flags.go
  swarm/network/hive.go
  swarm/network/kademlia.go
  swarm/network/protocol.go
  swarm/network/simulations/overlay_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
  swarm/pot/pot_test.go
  swarm/pss/api.go
  swarm/pss/client/client.go
  swarm/pss/client/doc.go
  swarm/pss/handshake.go
  swarm/pss/handshake_test.go
  swarm/pss/ping.go
  swarm/pss/protocol.go
  swarm/pss/protocol_test.go
  swarm/pss/pss.go
  swarm/services/swap/swap.go
  swarm/services/swap/swap/swap.go
  swarm/storage/chunker.go
  swarm/storage/common.go
  swarm/storage/ldbstore.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore.go
  swarm/storage/memstore_test.go
  swarm/storage/mock/rpc/rpc.go
  swarm/storage/mru/resource.go
  swarm/storage/netstore.go
  swarm/storage/pyramid.go
  swarm/storage/types.go
  swarm/swarm.go
Labels: ready for review

#671 Buffer for HandleGetFile's LazyChunkReader
  swarm/api/http/server.go
Labels: ready for review

#686 Add ldbstore quit channel to terminate running loops
  swarm/storage/ldbstore.go
Labels: ready for review

#695 swarm/storage: close channel only after we have replaced chunk in memStore
  swarm/storage/localstore.go
Labels: ready for review

#633 swarm/hash: Custom multihash implementation
  swarm/api/api.go
  swarm/api/http/server_test.go
  swarm/multihash/LICENSE
  swarm/multihash/Makefile
  swarm/multihash/README.md
  swarm/multihash/README_SWARM.md
  swarm/multihash/io.go
  swarm/multihash/multihash.go
  swarm/multihash/multihash_test.go
  swarm/multihash/package.json
  swarm/multihash/sum.go
  swarm/storage/mru/resource.go
  swarm/storage/mru/resource_test.go
Labels: enhancement, ready for another review

#656 Swarm network rewrite golint warnings
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/client/client_test.go
  swarm/api/filesystem.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/storage.go
  swarm/api/storage_test.go
  swarm/api/testapi.go
  swarm/fuse/swarmfs.go
  swarm/fuse/swarmfs_test.go
  swarm/fuse/swarmfs_unix.go
  swarm/swarm.go
  swarm/testutil/http.go
Labels: ready for review

#698 swarm/pss: Increment pss message version
  swarm/pss/pss.go
Labels: bug, pss

#692 swarm/fuse: disable fuse tests
  swarm/fuse/swarmfs_test.go
Labels: ready for review

#700 swarm/storage: do not close rh.chunkstore
  swarm/storage/mru/resource_test.go
Labels: ready for review

#701 swarm/storage: branches argument is not used, so remove it
  swarm/storage/chunker.go
Labels: ready for review

#691 BMT hasher rewrite
  swarm/api/http/server_test.go
  swarm/bmt/bmt.go
  swarm/bmt/bmt_r.go
  swarm/bmt/bmt_test.go
  swarm/storage/types.go
Labels: bmt, bug, enhancement, network rewrite, ready for another review

#708 Fix storage benchmark tests
  swarm/storage/common_test.go
  swarm/storage/filestore.go
  swarm/storage/filestore_test.go
  swarm/storage/ldbstore_test.go
  swarm/storage/memstore_test.go
Labels: ready for review, test

#706 Swarm network rewrite golint2
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/main.go
  eth/protocol.go
  les/protocol.go
  swarm/api/config.go
  swarm/api/filesystem.go
  swarm/api/http/error.go
  swarm/api/http/server.go
  swarm/api/manifest.go
  swarm/api/storage.go
  swarm/api/testapi.go
  swarm/pss/handshake.go
  swarm/pss/pss.go
  swarm/storage/chunker.go
  swarm/storage/database.go
  swarm/storage/dbapi.go
  swarm/storage/filestore.go
  swarm/storage/hasherstore.go
  swarm/storage/localstore.go
  swarm/storage/mru/resource.go
  swarm/storage/netstore.go
  swarm/storage/pyramid.go
  swarm/storage/swarmhasher.go
  swarm/storage/types.go
  swarm/swarm.go
  swarm/swarm_test.go
Labels: network rewrite, ready for review

#707 swarm/network: bump up bzz protocol version to 4, because of BMT hashes
  swarm/network/protocol.go
  swarm/network/protocol_test.go
  swarm/network/stream/stream.go
Labels: ready for review

#652 swarm: cleanup created resources for fuse
  swarm/fuse/fuse_dir.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_test.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
Labels: fuse, ready for another review, test

#711 Detect potential panics on short chunk data
  swarm/storage/chunker.go
  swarm/storage/mru/resource.go
  swarm/storage/types.go
Labels: ready for review

#714 Set ETag header with correct syntax
  swarm/api/http/server.go
Labels: ready for review

#712 swarm/pss: move EnableMetrics away from testutil
  swarm/pss/pss_test.go
  swarm/testutil/http.go
Labels: ready for review

#715 Downgrade 'invalid content address' error to trace log
  swarm/storage/localstore.go
  swarm/storage/types.go
Labels: ready for review

#717 vendor: remove unused libraries
  common/bytes.go
  p2p/nat/natupnp_test.go
  vendor/github.com/jbenet/go-base58/LICENSE
  vendor/github.com/jbenet/go-base58/README.md
  vendor/github.com/jbenet/go-base58/base58.go
  vendor/github.com/jbenet/go-base58/doc.go
  vendor/github.com/spaolacci/murmur3/LICENSE
  vendor/github.com/spaolacci/murmur3/README.md
  vendor/github.com/spaolacci/murmur3/murmur.go
  vendor/github.com/spaolacci/murmur3/murmur128.go
  vendor/github.com/spaolacci/murmur3/murmur32.go
  vendor/github.com/spaolacci/murmur3/murmur64.go
  vendor/golang.org/x/crypto/blake2b/blake2b.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_generic.go
  vendor/golang.org/x/crypto/blake2b/blake2b_ref.go
  vendor/golang.org/x/crypto/blake2b/register.go
  vendor/golang.org/x/crypto/blake2s/blake2s.go
  vendor/golang.org/x/crypto/blake2s/blake2s_386.go
  vendor/golang.org/x/crypto/blake2s/blake2s_386.s
  vendor/golang.org/x/crypto/blake2s/blake2s_amd64.go
  vendor/golang.org/x/crypto/blake2s/blake2s_amd64.s
  vendor/golang.org/x/crypto/blake2s/blake2s_generic.go
  vendor/golang.org/x/crypto/blake2s/blake2s_ref.go
  vendor/golang.org/x/crypto/blake2s/register.go
  vendor/golang.org/x/crypto/sha3/doc.go
  vendor/golang.org/x/crypto/sha3/hashes.go
  vendor/golang.org/x/crypto/sha3/keccakf.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.s
  vendor/golang.org/x/crypto/sha3/register.go
  vendor/golang.org/x/crypto/sha3/sha3.go
  vendor/golang.org/x/crypto/sha3/shake.go
  vendor/golang.org/x/crypto/sha3/xor.go
  vendor/golang.org/x/crypto/sha3/xor_generic.go
  vendor/golang.org/x/crypto/sha3/xor_unaligned.go
  vendor/leb.io/hashland/LICENSE
  vendor/leb.io/hashland/keccakpg/keccak.go
  vendor/vendor.json
  whisper/whisperv5/peer_test.go
  whisper/whisperv6/peer_test.go
Labels: ready for review

#713 Handle compress edge cases in pyramid chunker
  swarm/storage/pyramid.go
  swarm/swarm_test.go
Labels: ready for review

#720 swarm/api: update log.Output to report meaningful log line
  swarm/api/http/error.go
  swarm/log/log.go
Labels: ready for review

#724 just change the background color as per the suggestion by @homotopyco…
  swarm/api/http/error_templates.go
Labels: ready for review

#725 Add tests for buffered http get
  swarm/api/http/bufferedget_test.go
  swarm/api/http/server.go
Labels: ready for review

#723 swarm/pss: Update benchmark tests
  swarm/pss/pss_test.go
Labels: bug, pss, ready for review

#736 cmd/swarm: minor cli flag text adjustments
  cmd/swarm/main.go
Labels: ready for review

#737 Fix mingw test issues on windows
  cmd/swarm/fs_test.go
  swarm/storage/ldbstore_test.go
  swarm/swarm_test.go
Labels: ready for review

#752 Landing page fix 2
  swarm/api/http/error.go
  swarm/api/http/error_templates.go
  swarm/api/http/templates.go
Labels: http interface, ready for review

#754 swarm: propagate ctx to internal apis
  cmd/swarm/hash.go
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/filesystem.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/storage.go
  swarm/api/storage_test.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_test.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/syncer_test.go
  swarm/network_test.go
  swarm/storage/filestore.go
  swarm/storage/filestore_test.go
  swarm/swarm_test.go
Labels: ready for review

#760 swarm/metrics: collect disk measurements
  metrics/metrics.go
  swarm/metrics/flags.go
Labels: ready for review

#740 swarm: added network ID test
  swarm/network/networkid_test.go
Labels: ready for review
