Repository ethersphere/swarm, pull requests merged in 2018-05, with the labels that each got.

#467 swarm/api: add resetting timer for HTTP requests
  swarm/api/http/server.go
Labels: ready for review

#482 Change netstore retry timeout to 30s
  swarm/storage/netstore.go
Labels: ready for review

#487 swarm/pss: Pss tick leak fix
  swarm/pss/pss.go
Labels: bug, network rewrite, pss, ready for review

#485 swarm/network/stream: fix syncer ticker leak
  swarm/network/stream/syncer.go
Labels: ready for review

#470 swarm/api, swarm/storage: Resource api fixes
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/storage/resource.go
  swarm/swarm.go
Labels: bug, enhancement, ready for review, resource update

#478 swarm/storage: Add method for getting previous resource update
  swarm/storage/resource.go
  swarm/storage/resource_test.go
Labels: enhancement, ready for review, resource update

#415 swarm: fix broken overlay sim with rewrite
  p2p/simulations/adapters/state.go
  swarm/network/simulations/overlay.go
  swarm/network/simulations/overlay_test.go
Labels: ready for another review, ready for review

#488 swarm/pss: Restore lost expiry handler for incoming messages
  swarm/pss/pss.go
  swarm/pss/pss_test.go
Labels: bug, pss, ready for review

#383 swarm: Added cache-control headers to maximize downstream caching of immutable content
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/storage.go
  swarm/api/uri.go
  swarm/api/uri_test.go
  swarm/network_test.go
Labels: http interface, ready for review

#494 swarm/api/http: handle disallowed posts correctly
  swarm/api/http/server.go
  swarm/api/http/server_test.go
Labels: http interface, ready for review

#491 Manifest read size limit
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/network/simulations/overlay_test.go
  swarm/storage/resource.go
Labels: ready for review

#495 swarm/storage: add counters for lazychunkreader
  swarm/storage/chunker.go
Labels: ready for review

#496 swarm/storage: Fix specific version select on period flip
  swarm/storage/resource.go
Labels: bug, ready for review, resource update

#506 swarm/storage: counters for errors and bytes for LazyChunkReader
  swarm/storage/chunker.go
Labels: ready for review

#508 swarm/pss: Disable failing test for message handler
  swarm/pss/pss_test.go
Labels: bug, pss, ready for review

#510 swarm/network: debug high disk utilisation
  swarm/network/stream/messages.go
  swarm/network/stream/syncer.go
Labels: ready for review

#511 swarm/network: add counter before iterator
  swarm/network/stream/syncer.go
Labels: ready for review

#498 p2p/sim: use RandomNodeConfig() to init nodes
  cmd/p2psim/main.go
Labels: ready for review

#514 swarm/network: revert change in timer
  swarm/network/stream/syncer.go
Labels: ready for review

#515 swarm/storage: ldbstore garbage collection counters
  swarm/storage/ldbstore.go
Labels: ready for review

#522 swarm/storage: basic measurements for LDBStore and LDBDatabase
  swarm/storage/database.go
  swarm/storage/ldbstore.go
Labels: ready for review

#523 Always add intervals in client.batchDone
  swarm/network/stream/stream.go
Labels: ready for review

#524 swarm/storage: remove redundant counter
  swarm/storage/ldbstore.go
  swarm/storage/localstore.go
Labels: ready for review

#526 swarm/storage: measurements on getorcreaterequest
  swarm/storage/localstore.go
Labels: ready for review

#503 swarm: Use syncenabled flag in streamer initializer
  swarm/swarm.go
Labels: bug, ready for review

#531 Write to LDBStore.batchesC on tryAccessIdx
  swarm/storage/ldbstore.go
Labels: ready for review

#502 swarm/storage, swarm/api: Fix parseUpdate for multihash
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/storage/error.go
  swarm/storage/resource.go
Labels: bug, ready for review, resource update

#513 swarm/storage: Add timeout to netstore private get
  swarm/storage/netstore.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/swarm.go
Labels: bug, ready for review, resource update

#499 removed deprecated cli flags
  cmd/swarm/config.go
  cmd/swarm/main.go
Labels: ready for review

#532 swarm/network: better classify of log message
  swarm/network/stream/messages.go
  swarm/network/stream/stream.go
Labels: ready for review

#504 swarm/storage: Check period over- and underflow values
  swarm/storage/resource.go
Labels: bug, ready for review, resource update

#507 swarm/storage: Replace localstore with netstore for mutable resource
  swarm/storage/resource.go
  swarm/swarm.go
Labels: bug, ready for review, resource update

#534 swarm/pss: Protocol RemovePeer
  swarm/pss/client/client.go
  swarm/pss/client/client_test.go
  swarm/pss/protocol.go
  swarm/pss/protocol_test.go
Labels: enhancement, pss, ready for review

#548 Add DeliverySkipCheck flag and tests
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/main.go
  swarm/api/config.go
  swarm/network/stream/common_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/syncer_test.go
  swarm/network_test.go
  swarm/swarm.go
Labels: ready for review

#550 Increase overlay sim test timeout
  swarm/network/simulations/overlay_test.go
Labels: network rewrite, network testing, ready for review

#463 cmd/swarm: add swarm down
  cmd/swarm/download.go
  cmd/swarm/main.go
  cmd/swarm/upload.go
  cmd/swarm/upload_test.go
  swarm/api/client/client.go
Labels: ready for another review

#557 Add TestNewSwarm and simplify NewSwarm constructor
  cmd/swarm/main.go
  swarm/api/client/client.go
  swarm/api/config.go
  swarm/network_test.go
  swarm/swarm.go
  swarm/swarm_test.go
Labels: ready for review

#558 swarm, swarm/storage: use MultiResolver for resource ownerValidator
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/swarm.go
  swarm/testutil/http.go
Labels: ready for review

#590 p2p, swarm: measure number of p2p.Send calls and time them
  p2p/protocols/protocol.go
  swarm/network/stream/peer.go
  swarm/network/stream/stream.go
Labels: ready for review

#538 swarm/network: fix NetworkID config
  swarm/api/config.go
  swarm/network/hive.go
  swarm/network/protocol.go
  swarm/network/protocol_test.go
  swarm/swarm.go
Labels: ready for review

#597 p2p, swarm: use different names for counter and timer
  p2p/protocols/protocol.go
  swarm/network/stream/peer.go
Labels: ready for review

#596 Disable TestOverlaySim
  swarm/network/simulations/overlay_test.go
Labels: ready for review, test

#589 swarm-network-rewrite conflicts with master
  core/tx_list.go
  core/tx_pool.go
  core/tx_pool_test.go
  core/vm/instructions.go
  p2p/simulations/network.go
  trie/iterator.go
  trie/proof_test.go
Labels: ready for review

#599 resolve conflicts with master - second attempt
  eth/backend.go
  node/doc.go
  trie/hasher.go
  trie/trie.go
Labels: ready for review

#541 swarm/storage, swarm/api: Content addressed root chunks for MRU
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/testutil/http.go
Labels: bug, enhancement, ready for review, resource update

#575 swarm/pss: Add GetPeerTopics, GetPeerAddress api method
  swarm/pss/api.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
Labels: enhancement, pss, ready for another review

#543 cmd/swarm: add CLI to FUSE
  cmd/swarm/fs.go
  cmd/swarm/fs_test.go
  cmd/swarm/main.go
  cmd/swarm/run_test.go
  swarm/fuse/fuse_dir.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
Labels: ready for another review

#603 bmt, pot: move into swarm package
  swarm/bmt/bmt.go
  swarm/bmt/bmt_r.go
  swarm/bmt/bmt_test.go
  swarm/network/discovery.go
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/stream.go
  swarm/pot/address.go
  swarm/pot/doc.go
  swarm/pot/pot.go
  swarm/pot/pot_test.go
  swarm/pss/client/doc.go
  swarm/pss/pss.go
  swarm/storage/types.go
Labels: network rewrite, ready for review

#622 swarm/network/stream/delivery: byte comparison on error nil
  swarm/network/stream/delivery.go
Labels: bug, ready for review

#629 swarm/fuse: do not support relative path for fuse mounting
  cmd/swarm/fs.go
  swarm/fuse/swarmfs_unix.go
Labels: bug, ready for review

#636 Fix panic in p2psim
  p2p/simulations/network.go
Labels: ready for review

#643 Rename storage.Key to storage.Address
  cmd/swarm/hash.go
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/filesystem.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/api/storage.go
  swarm/api/uri.go
  swarm/api/uri_test.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/peer.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network_test.go
  swarm/storage/chunker.go
  swarm/storage/chunker_test.go
  swarm/storage/chunkstore.go
  swarm/storage/common_test.go
  swarm/storage/dbapi.go
  swarm/storage/dpa.go
  swarm/storage/hasherstore.go
  swarm/storage/ldbstore.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore.go
  swarm/storage/memstore.go
  swarm/storage/memstore_test.go
  swarm/storage/mock/test/test.go
  swarm/storage/netstore.go
  swarm/storage/netstore_test.go
  swarm/storage/pyramid.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/storage/types.go
  swarm/swarm.go
Labels: ready for review, storage-refactor

#561 swarm/storage: Separate mutable resources into separate package
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/storage/chunker.go
  swarm/storage/common.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore_test.go
  swarm/storage/mru/error.go
  swarm/storage/mru/resource.go
  swarm/storage/mru/resource_sign.go
  swarm/storage/mru/resource_test.go
  swarm/storage/netstore.go
  swarm/storage/resource_sign.go
  swarm/swarm.go
  swarm/testutil/http.go
Labels: enhancement, ready for review, resource update

#651 Swarm network rewrite addrnew
  cmd/swarm/hash.go
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/filesystem.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/api/storage.go
  swarm/api/uri.go
  swarm/api/uri_test.go
  swarm/fuse/fuse_file.go
  swarm/fuse/swarmfs_unix.go
  swarm/fuse/swarmfs_util.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/peer.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network_test.go
  swarm/storage/chunker.go
  swarm/storage/chunker_test.go
  swarm/storage/chunkstore.go
  swarm/storage/common.go
  swarm/storage/common_test.go
  swarm/storage/dbapi.go
  swarm/storage/dpa.go
  swarm/storage/hasherstore.go
  swarm/storage/ldbstore.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore.go
  swarm/storage/localstore_test.go
  swarm/storage/memstore.go
  swarm/storage/memstore_test.go
  swarm/storage/mock/test/test.go
  swarm/storage/mru/resource.go
  swarm/storage/mru/resource_test.go
  swarm/storage/netstore.go
  swarm/storage/netstore_test.go
  swarm/storage/pyramid.go
  swarm/storage/types.go
  swarm/swarm.go
Labels: enhancement, ready for review, resource update

#635 Fix panic: do not set nil resolver for interface types
  swarm/swarm.go
Labels: bug, ready for review

#540 make topic readable in error messages
  swarm/pss/pss.go
Labels: pss, ready for review
