Repository ethersphere/swarm, pull requests merged in 2018-04, with the labels that each got.

#354 swarm/pss: Forward-failsafe outbox
  swarm/pss/handshake.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
Labels: pss, ready for review

#358 cmd/swarm-smoke: smoke tests for the test cluster
  cmd/swarm/swarm-smoke/main.go
  cmd/swarm/swarm-smoke/upload_and_sync.go
Labels: ready for review

#276 Swarm network rewrite snapshot test
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/streamer_test.go
  swarm/network/stream/syncer.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/snapshot_128.json
  swarm/network/stream/testing/snapshot_16.json
  swarm/network/stream/testing/snapshot_256.json
  swarm/network/stream/testing/snapshot_32.json
  swarm/network/stream/testing/snapshot_64.json
  swarm/network/stream/testing/testing.go
Labels: network rewrite, ready for review

#366 swarm/pss: Deduplication of messages
  swarm/pss/client/client_test.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/pss/types.go
  swarm/swarm.go
Labels: pss, ready for review

#272 swarm: migrated overlay sim to network rewrite
  p2p/simulations/mocker.go
  swarm/network/simulations/overlay.go
Labels: ready for another review

#356 Encryption integration into swarm API
  swarm/api/api.go
  swarm/api/api_test.go
  swarm/api/filesystem.go
  swarm/api/filesystem_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/api/storage.go
  swarm/api/storage_test.go
  swarm/fuse/swarmfs_test.go
  swarm/storage/dpa.go
Labels: encryption, ready for review

#367 Add PSS fwd cache cleaning
  swarm/pss/pss.go
  swarm/pss/pss_test.go
Labels: pss, ready for review

#379 Kademlia fixes
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/simulations/discovery/discovery_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/testing/snapshot_128.json
  swarm/network/stream/testing/snapshot_16.json
  swarm/network/stream/testing/snapshot_256.json
  swarm/network/stream/testing/snapshot_32.json
  swarm/network/stream/testing/snapshot_64.json
Labels: network rewrite, ready for review

#385 Stream test RPC unsubscribe deadlock
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/syncer_test.go
  swarm/network/stream/testing/testing.go
Labels: ready for review, swarm-network-rewrite

#380 Command line encryption api
  cmd/swarm/main.go
  cmd/swarm/manifest.go
  cmd/swarm/upload.go
  cmd/swarm/upload_test.go
  swarm/api/api.go
  swarm/api/client/client.go
  swarm/api/client/client_test.go
  swarm/api/filesystem.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/api/manifest.go
  swarm/api/manifest_test.go
  swarm/fuse/fuse_file.go
  swarm/network/stream/common_test.go
  swarm/storage/dpa.go
  swarm/storage/dpa_test.go
Labels: encryption, ready for another review

#337 Abstraction of chunk data validation
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/db.go
  cmd/swarm/main.go
  swarm/api/api.go
  swarm/api/config.go
  swarm/api/config_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/fuse/swarmfs_test.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/testing/testing.go
  swarm/storage/dpa.go
  swarm/storage/dpa_test.go
  swarm/storage/error.go
  swarm/storage/ldbstore.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore.go
  swarm/storage/localstore_test.go
  swarm/storage/memstore.go
  swarm/storage/memstore_test.go
  swarm/storage/netstore.go
  swarm/storage/netstore_test.go
  swarm/storage/resource.go
  swarm/storage/resource_ens.go
  swarm/storage/resource_sign.go
  swarm/storage/resource_test.go
  swarm/storage/types.go
  swarm/swarm.go
  swarm/testutil/http.go
  vendor/github.com/naoina/toml/encode.go
  vendor/github.com/naoina/toml/parse.go
  vendor/github.com/naoina/toml/parse.peg
  vendor/github.com/naoina/toml/parse.peg.go
  vendor/vendor.json
Labels: network rewrite, ready for another review

#387 swarm: implemented retrieval test
  swarm/network/stream/common_test.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
Labels: in progress, network rewrite, ready for review

#363 new impl for MemStore ; refactor of collectGarbage ; tests for MemStore, LDBStore and collectGarbage
  cmd/swarm/db.go
  metrics/timer_test.go
  swarm/network/stream/common_test.go
  swarm/network/stream/intervals/store_test.go
  swarm/network/stream/intervals_test.go
  swarm/pss/client/client_test.go
  swarm/pss/pss_test.go
  swarm/state/inmemorystore.go
  swarm/storage/common_test.go
  swarm/storage/dpa.go
  swarm/storage/dpa_test.go
  swarm/storage/ldbstore.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore.go
  swarm/storage/memstore.go
  swarm/storage/memstore_test.go
  swarm/storage/mock/mem/mem_test.go
  swarm/storage/types.go
  swarm/swarm.go
Labels: network rewrite, ready for another review

#299 cmd/swarm: make sure swarm doesnt crash when requested missing hashes
  cmd/swarm/upload_test.go
Labels: ready for review

#389 Use Bmt hash for swarm
  swarm/multihash/LICENSE
  swarm/multihash/Makefile
  swarm/multihash/README.md
  swarm/multihash/README_SWARM.md
  swarm/multihash/io.go
  swarm/multihash/multihash.go
  swarm/multihash/package.json
  swarm/multihash/sum.go
  swarm/pss/pss.go
  swarm/storage/common_test.go
  swarm/storage/dpa.go
  swarm/storage/hasherstore_test.go
  swarm/storage/ldbstore_test.go
  swarm/storage/localstore_test.go
  swarm/storage/memstore_test.go
  swarm/storage/resource_test.go
  swarm/storage/swarmhasher.go
  swarm/storage/types.go
  swarm/swarm.go
  swarm/testutil/http.go
  vendor/vendor.json
Labels: network rewrite, ready for review

#398 Fix flaky FUSE tests
  swarm/fuse/swarmfs_test.go
Labels: network rewrite, ready for review

#393 swarm/fuse: fix race condition
  swarm/fuse/swarmfs_test.go
Labels: ready for review

#406 swarm/network: Remove pruning implementation
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/simulations/overlay.go
Labels: network rewrite, ready for review

#416 swarm: tracing to help fix `unexpected EOF`
  cmd/swarm/swarm-smoke/upload_and_sync.go
  swarm/api/api.go
  swarm/network/stream/syncer.go
  swarm/storage/chunker.go
  swarm/storage/dpa.go
Labels: ready for review

#424 swarm/api: get rid of swarm-gateways.net urls
  swarm/api/http/error_templates.go
  swarm/api/http/templates.go
Labels: ready for review

#422 swarm: Change sync params to neg. assert + remove optnl pss/resource
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/main.go
  swarm/api/config.go
  swarm/network_test.go
  swarm/swarm.go
Labels: bug, ready for another review

#429 Fix LazyChunkReader.ReadAt()
  swarm/storage/chunker.go
  swarm/storage/chunker_test.go
Labels: network rewrite, ready for review

#432 swarm/network: counters for outgoing/incoming requests for chunks
  swarm/network/stream/delivery.go
Labels: ready for review

#435 swarm/storage: remove log for evict outgoing request
  swarm/storage/memstore.go
Labels: ready for review

#430 swarm: remove double stream protocol in protocols
  swarm/swarm.go
Labels: network rewrite, ready for review

#437 swarm/network: bump versions for protocols bzz, hive and stream to 3
  swarm/network/protocol.go
  swarm/network/protocol_test.go
  swarm/network/stream/common_test.go
  swarm/network/stream/stream.go
  swarm/swarm.go
Labels: network rewrite, ready for review

#448 Raise search timeout for NetStore to 30s
  swarm/storage/dpa.go
Labels: ready for review

#449 cmd/swarm: log error on upload
  cmd/swarm/swarm-smoke/upload_and_sync.go
  swarm/api/api.go
Labels: ready for review

#453 swarm/api: move debug line to avoid panic
  swarm/api/api.go
Labels: ready for review

#455 swarm/api: remove redundant log line
  swarm/api/http/server.go
  swarm/storage/localstore.go
  swarm/swarm.go
Labels: ready for review

#456 Fix hashMatcher
  swarm/api/api.go
Labels: ready for review

#469 swarm: fixed linter errors
  swarm/api/http/server.go
  swarm/network/protocol.go
  swarm/network/protocol_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/syncer.go
  swarm/pss/client/client_test.go
  swarm/pss/pss.go
  swarm/pss/pss_test.go
  swarm/storage/chunker.go
  swarm/storage/ldbstore.go
Labels: ready for review

#466 NetStore Get retry
  swarm/storage/dpa.go
  swarm/storage/netstore.go
  swarm/storage/netstore_test.go
Labels: ready for review

#417 swarm/api, swarm/storage: Multihash handling in swarm api for resource updates
  swarm/api/api.go
  swarm/api/http/error_test.go
  swarm/api/http/server.go
  swarm/api/http/server_test.go
  swarm/storage/resource.go
  swarm/storage/resource_test.go
  swarm/testutil/http.go
Labels: enhancement, ready for review, resource update

#472 swarm/api: Correct signature for test server in api client test
  swarm/api/client/client_test.go
Labels: bug

#443 swarm: removed deprecated PUT apis
  swarm/api/api.go
  swarm/api/http/server.go
  swarm/api/uri.go
  swarm/api/uri_test.go
Labels: ready for review

#475 swarm/pss: Remove redundant run func param to addpeer
  swarm/pss/protocol.go
  swarm/pss/protocol_test.go
Labels: bug, pss, ready for review

#474 swarm/network: Change Peerinfo output to hexutil.Bytes
  swarm/network/hive.go
Labels: bug
