Repository ethersphere/swarm, pull requests merged in 2019-10, with the labels that each got.

#1846 network: fix hive autoconnect param for non-snapshot tests
  network/stream/cursors_test.go
  network/stream/syncing_test.go
Labels: bug, ready for review, test

#1829 simulation: skip docker tests locally
  simulation/docker_test.go
  simulation/examples/snapshot/docker_test.go
Labels: cleanup, test

#1852 chunk, cmd/swarm: return last tag
  chunk/tags.go
  cmd/swarm/upload.go
Labels: tags

#1851 api/client: use a separate http client with cookie jar for sticky sesions
  api/client/client.go
Labels: ready for review

#1850 cmd/swarm: remove --no-track, add --progress flag
  cmd/swarm/access_test.go
  cmd/swarm/export_test.go
  cmd/swarm/flags.go
  cmd/swarm/fs_test.go
  cmd/swarm/manifest_test.go
  cmd/swarm/upload.go
  cmd/swarm/upload_test.go
Labels: on hold

#1827 swap: message price
  cmd/swarm/config_test.go
  swap/config.go
  swap/prices.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#1853 cmd/swarm: fix progress bars for encrypted uploads
  cmd/swarm/upload.go
Labels: bug, ready for review

#1862 cmd/swarm: only use the default bootnodes on the default network id
  cmd/swarm/main.go
Labels: ready for review

#1859 api/http: add HTML Progress Bar
  api/http/server.go
  api/http/server_test.go
  api/http/templates.go
Labels: enhancement, http interface, tags

#1828 api, chunk, storage: anonymous uploads
  api/api_test.go
  api/client/client.go
  api/client/client_test.go
  api/http/middleware.go
  api/http/server.go
  api/http/server_test.go
  chunk/chunk.go
  chunk/tag.go
  chunk/tag_test.go
  chunk/tags.go
  chunk/tags_test.go
  cmd/swarm-smoke/util.go
  cmd/swarm/access.go
  cmd/swarm/access_test.go
  cmd/swarm/flags.go
  cmd/swarm/manifest.go
  cmd/swarm/upload.go
  network/stream/sync_provider.go
  network_test.go
  pushsync/pusher.go
  pushsync/pusher_test.go
  pushsync/simulation_test.go
  storage/chunker_test.go
  storage/filestore.go
  storage/hasherstore_test.go
  storage/localstore/gc_test.go
  storage/localstore/index_test.go
  storage/localstore/localstore.go
  storage/localstore/localstore_test.go
  storage/localstore/mode_get_test.go
  storage/localstore/mode_set.go
  storage/localstore/mode_set_test.go
  storage/localstore/retrieval_index_test.go
  storage/pin/pin.go
  swarm.go
  swarm_test.go
Labels: ready for review

#1871 simulation/examples: disable docker test from running locally
  api/http/templates.go
  simulation/examples/cluster/cluster_test.go
Labels: test

#1874 chunk: align Tag fields for atomic operations on 32bit architectures
  chunk/tag.go
Labels: ready for review

#1737 Incentives first sim
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for another review

#1870 pss: fix concurrent map read and map write on pubKeyRWPool
  pss/protocol.go
Labels: ready for review

#1806 swarm, swap: add addresses to logs
  swap/peer.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives, ready for another review

#1860 pss: Limit the number of workers forwarding messages in outbox
  pss/outbox/message.go
  pss/outbox/mock.go
  pss/outbox/outbox.go
  pss/outbox/outbox_test.go
  pss/outbox/outbox_whitebox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/types.go
Labels: bug, pss, ready for review

#1861 pss: Limit by time the retries of messages in the outbox
  pss/outbox/message.go
  pss/outbox/outbox.go
  pss/outbox/outbox_test.go
  pss/outbox/outbox_whitebox_test.go
  pss/pss.go
Labels: pss, ready for review

#1844 network: Reconnect to the same peers on startup
  network/hive.go
  network/hive_test.go
Labels: kademlia, priority, ready for review

#1888 testutil: remove pre Go 1.13 support
  testutil/init.go
  testutil/init_go1.13.go
Labels: ready for review

#1889 build: configure golangci-lint timeout in .golangci.yml
  .golangci.yml
  build/ci.go
Labels: ready for review

#1890 build, .travis.yml, Makefile, README.md: remove GO111MODULE=on
  .travis.yml
  Makefile
  README.md
  build/ci.go
  build/env.sh
Labels: ready for review

#1875 retrieve: block unsolicited chunk deliveries
  network/protocol.go
  network/protocol_test.go
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/retrieval/wire.go
  simulation/examples/cluster/cluster_test.go
Labels: bug, enhancement, incentives, ready for review

#1891 state: avoid has call and remove error shadowing in Get
  state/dbstore.go
Labels: ready for review

#1878 storage/pin: fix getAllChunksFromDB test function
  storage/pin/pin_test.go
Labels: bug, pinning

#1896 netkwork/hive: addPeer function assigned after launching goroutine co…
  network/hive.go
Labels: bug, hive, ready for review

#1898 api/http: fix bufferedReadSeeker Seek method
  api/http/readseeker_test.go
  api/http/server.go
Labels: ready for review

#1880 chunk, pushsync: do not increment synced tags in pushsync
  chunk/tag.go
  cmd/swarm/upload.go
  pushsync/pusher.go
  pushsync/pusher_test.go
  pushsync/simulation_test.go
Labels: ready for review

#1881 pushsync: split sync to chunksWorker and receiptsWorker
  pushsync/pusher.go
  pushsync/pusher_test.go
Labels: ready for review

#1904 pushsync: fix finish root span
  pushsync/pusher.go
Labels: ready for review

#1905 pusher: db.Set before check for synced
  cmd/swarm-smoke/upload_and_sync.go
  pushsync/pusher.go
Labels: ready for review

#1906 chunk: align tag struct for 32bit arch
  chunk/tag.go
Labels: ready for review

#1908 api,storage: add index size rpc call for debugging
  api/inspector.go
  api/inspector_test.go
  storage/localstore/localstore.go
  storage/localstore/localstore_test.go
  swarm.go
Labels: ready for review

#1901 Fix Hive data races
  network/hive.go
  network/hive_test.go
Labels: ready for review

#1900 Fix pss data races
  pss/internal/ticker/ticker.go
  pss/pss.go
Labels: ready for review

#1909 storage/localstore: do not later batch in setSync if moveToGc is false
  storage/localstore/mode_set.go
  storage/localstore/mode_set_test.go
Labels: ready for review

#1912 shed: allow to change index name for easier migrations
  shed/schema.go
  shed/schema_test.go
Labels: ready for review

#1801 network: move hive message handler from Peer type
  network/hive.go
  network/peer.go
  network/peer_test.go
Labels: cleanup, enhancement, kademlia, ready for another review

#1833 network/kademlia: SugestPeer funcionality. Variable number of min peers per bin
  network/kademlia.go
  network/kademlia_test.go
Labels: enhancement, kademlia, ready for review

#1892 Swap available balance
  contracts/swap/swap.go
  swap/protocol.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#1863 swap: expand RPC calls for cheque info querying
  swap/protocol.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for another review

#1916 pss: Pushsync and PSS fixes
  pss/api.go
  pss/outbox/mock.go
  pss/outbox/outbox.go
  pss/outbox/outbox_test.go
  pss/outbox/outbox_whitebox_test.go
  pss/pss.go
  pss/pubsub.go
  pushsync/simulation_test.go
  swarm.go
Labels: enhancement, pss, push-sync, ready for review
