Repository ethersphere/swarm, pull requests merged in 2019-11, with the labels that each got.

#1914 chunk: fix tag Sent value on load, dont persist done tags
  chunk/tags.go
Labels: bug, ready for review

#1924 network/stream: fix slice append bug
  network/stream/stream.go
Labels: bug, stream

#1923 swarm: shutdown pushsync before pss
  swarm.go
Labels: bug

#1927 network/stream: fix stream test data race
  network/stream/cursors_test.go
Labels: bug, flaky test

#1887 swap: introduce pending cheques, drop peers on io errors
  swap/cheque.go
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
Labels: incentives, ready for another review

#1873 swap: improve balance tests
  swap/swap_test.go
Labels: incentives, ready for review

#1930 swap: fix instabilities in simulation tests
  swap/simulations_test.go
Labels: incentives

#1937 swap: fixed bug which needs cheques to be confirmed
  swap/simulations_test.go
Labels: incentives, test

#1876 Lookahead buffer for ServeContent
  api/http/langos/buffered_reader.go
  api/http/langos/http_test.go
  api/http/langos/langos.go
  api/http/langos/langos_test.go
  api/http/langos/readseeker_test.go
  api/http/server.go
Labels: ready for review

#1774 network: Kademlia Load Balancing
  network/hive_test.go
  network/kademlia.go
  network/kademlia_load_balancer.go
  network/kademlia_load_balancer_test.go
  network/kademlia_test.go
  network/networkid_test.go
  network/peer.go
  network/pubsubchannel/pubsub.go
  network/pubsubchannel/pubsub_test.go
  network/resourceusestats/resource_use_stats.go
  pot/pot.go
  pot/pot_test.go
  pss/forwarding_test.go
  pss/pss.go
Labels: kademlia, ready for another review

#1942 swap: also wait for the debit counter to reach maxMsgsInt64
  swap/simulations_test.go
Labels: incentives, ready for review

#1913 swap: exchange chain id on handshake
  swap/protocol.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
Labels: incentives, ready for review

#1944 swap: fix a rare panic in TestMultiChequeSimulation
  swap/simulations_test.go
Labels: incentives, ready for review

#1926 integration-tests: config for set of integration tests for stable swarm
  integration-tests/stable/.env
  integration-tests/stable/deployment.yaml
  integration-tests/stable/deployment/private-smoke-a.yaml
  integration-tests/stable/deployment/private-swarm.yaml
  integration-tests/stable/deployment/version.yaml
Labels: ready for review

#1907 cmd/swarm-smoke-pss: initial pss smoke tests
  cmd/swarm-smoke-pss/main.go
  cmd/swarm-smoke-pss/pss.go
  cmd/swarm-smoke-pss/util.go
  docker/run-smoke.sh
Labels: ready for review

#1883 swap: segregate api code and tests
  swap/api.go
  swap/api_test.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: cleanup, incentives, ready for review

#1922 swap: always allow debt-reducing messages
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#1940 localstore: fix index leak when NN chunks enter localstore
  network/kademlia.go
  storage/localstore/localstore.go
  storage/localstore/mode_put.go
  storage/localstore/mode_put_test.go
  swarm.go
Labels: bug, ready for review

#1915 pushsync, localstore: decouple push/pull indexes for tag increment
  pushsync/pusher.go
  storage/localstore/localstore.go
  storage/localstore/migration.go
  storage/localstore/migration_test.go
  storage/localstore/mode_get_multi.go
  storage/localstore/mode_get_multi_test.go
  storage/localstore/mode_put.go
  storage/localstore/mode_set.go
  storage/localstore/mode_set_test.go
  storage/localstore/schema.go
  storage/localstore/testdata/sanctuary/000002.log
  storage/localstore/testdata/sanctuary/CURRENT
  storage/localstore/testdata/sanctuary/CURRENT.bak
  storage/localstore/testdata/sanctuary/LOCK
  storage/localstore/testdata/sanctuary/LOG
  storage/localstore/testdata/sanctuary/MANIFEST-000003
Labels: cleanup

#1947 api/http/langos: ensure only one second peek
  api/http/langos/langos.go
  api/http/langos/langos_test.go
Labels: ready for review

#1945 cmd/swarm: swap --sync-mode flag with --no-sync flag
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
Labels: cleanup, ready for review

#1919 bzzeth: Phase2 of bzz eth protocol
  bzzeth/bzzeth.go
  bzzeth/bzzeth_test.go
  bzzeth/peer.go
  bzzeth/wire.go
Labels: blockchain-on-swarm, ready for review

#1957 api/config: enable pushsync by default
  api/config.go
Labels: cleanup

#1952 network/stream: fix flaky tests and first delivered batch of chunks for an unwanted stream
  network/stream/common_test.go
  network/stream/cursors_test.go
  network/stream/snapshot_sync_test.go
  network/stream/stream.go
  network/stream/syncing_test.go
Labels: bug, flaky test, ready for review

#1960 cmd/swarm: add pprof custom profiles through flags
  cmd/swarm/flags.go
  cmd/swarm/main.go
Labels: cli

#1934 swap: use p2ptest for protocol tests
  swap/protocol_test.go
Labels: incentives, ready for review, test

#1962 pss, network: remove spamming loglines
  network/resourceusestats/resource_use_stats.go
  pss/outbox/outbox.go
Labels: cleanup

#1959 api: Add bzz-feed-raw scheme to retrieve arbitary feed update
  api/api.go
  api/http/server.go
  api/http/server_test.go
  api/http/test_server.go
  api/uri.go
  storage/feed/handler.go
  storage/feed/testutil.go
Labels: enhancement, ready for review

#1970 localstore: fix data races on subscriptions
  storage/localstore/subscription_pull.go
  storage/localstore/subscription_push.go
Labels: core

#1969 smoke: remove redundant check for bail flag
  cmd/swarm-smoke/upload_and_sync.go
Labels: bug

#1979 network: increase fetcher timeout
  network/stream/stream.go
  network/timeouts/timeouts.go
Labels: ready for review, stability

#1980 storage/localstore: add subscriptions wait group before closing leveldb
  network/stream/stream.go
  storage/localstore/localstore.go
  storage/localstore/subscription_pull.go
  storage/localstore/subscription_push.go
Labels: bug, ready for review

#1973 localstore: fix subscribe push iterator tag value
  network/stream/cursors_test.go
  storage/localstore/mode_set.go
  storage/localstore/subscription_push.go
Labels: bug, ready for review

#1978 localstore: change gc batch size
  storage/localstore/gc.go
Labels: ready for review

#1958 all: remove unused configuration settings
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  network_test.go
Labels: cleanup, cli, ready for review

#1972 stream: limit the number of peers we sync with on bin 0
  network/stream/cursors_test.go
  network/stream/sync_provider.go
Labels: enhancement, ready for review

#1974 swarm: release v0.5.3
  CHANGELOG.md
  version/version.go
Labels: ready for review

#1989 shed: RenameIndex return true if index is already renamed
  shed/schema.go
Labels: ready for review

#1992 localstore: skip tag not found on migration
  chunk/tags.go
  storage/localstore/migration.go
Labels: bug

#1993 stream: avoid repeated SetSyncPull for chunk, change batch size
  network/stream/stream.go
  network/stream/sync_provider.go
Labels: enhancement
