Repository ethersphere/swarm, pull requests merged in 2019-12, with the labels that each got.

#2001 api/http: use swarm.eth instead theswarm.eth in html templates
  api/http/templates.go
Labels: ready for review

#1964 swap, contracts, vendor: move to ERC20
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  contracts/swap/factory.go
  contracts/swap/swap.go
  go.mod
  go.sum
  swap/config.go
  swap/prices.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-1/simpleswap/code.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-1/simpleswap/simpleswap.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-1/simpleswapfactory/code.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-1/simpleswapfactory/simpleswapfactory.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-2-0/erc20simpleswap/code.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-2-0/erc20simpleswap/erc20simpleswap.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-2-0/simpleswapfactory/code.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-2-0/simpleswapfactory/simpleswapfactory.go
  vendor/modules.txt
Labels: incentives, ready for review

#1982 storage/netstore: optimize fetchers for faster forwarding
  network/timeouts/timeouts.go
  storage/netstore.go
Labels: network, ready for review, stability

#2000 all:bzzaddr instead of just overlay for logging
  api/inspector_test.go
  bzzeth/bzzeth_test.go
  cmd/swarm-snapshot/create.go
  network/kademlia_load_balancer_test.go
  network/kademlia_test.go
  network/network.go
  network/networkid_test.go
  network/protocol.go
  network/protocol_test.go
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/simulation/example_test.go
  network/simulation/kademlia_test.go
  network/simulation/node_test.go
  network/simulation/simulation.go
  network/simulations/discovery/discovery_test.go
  network/simulations/overlay.go
  network/stream/common_test.go
  network/stream/cursors_test.go
  network/stream/peer.go
  network/stream/stream.go
  network/stream/sync_provider.go
  network/stream/syncing_test.go
  pss/client/client_test.go
  pss/forwarding_test.go
  pss/notify/notify_test.go
  pss/prox_test.go
  pss/pss_test.go
  pushsync/simulation_test.go
  storage/feed/testutil.go
  storage/netstore.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: ready for review

#1999 storage/localstore: decode tags in push index only if it is complete
  storage/localstore/localstore.go
Labels: ready for review

#2015 log, network, storage, testutil: Log base address only in tests
  log/log.go
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/stream/cursors_test.go
  network/stream/peer.go
  network/stream/stream.go
  network/stream/sync_provider.go
  storage/netstore.go
  testutil/init.go
Labels: ready for review

#2016 storage: Preserve counter across Encrypt() calls
  storage/encryption/encryption.go
  storage/encryption/encryption_test.go
Labels: encryption, enhancement

#2023 swap: added cheques metrics
  swap/peer.go
  swap/swap.go
Labels: incentives

#2053 swap: pass the context to waitForTx directly
  contracts/swap/factory.go
  contracts/swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#2059 cmd, tracing: decouple cli from tracing package
  cmd/swarm-smoke-pss/main.go
  cmd/swarm-smoke/flags.go
  cmd/swarm-smoke/main.go
  cmd/swarm/main.go
  internal/flags/tracing.go
  tracing/tracing.go
Labels: ready for review

#2060 cmd/swarm, internal/debug: decouple cli library from internal/debug
  cmd/swarm/debug.go
  cmd/swarm/main.go
  internal/debug/flags.go
Labels: ready for review

#2061 swap: pass depositAmount to testDeploy
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap_test.go
Labels: incentives, ready for review

#2057 cmd, metrics: decouple metrics and cli library
  cmd/swarm-smoke-pss/main.go
  cmd/swarm-smoke/flags.go
  cmd/swarm-smoke/main.go
  cmd/swarm/main.go
  internal/flags/metrics.go
  metrics/flags.go
Labels: ready for review

#2056 api, cmd/swarm: remove unused cli context from act functions
  api/act.go
  cmd/swarm/access.go
Labels: ready for review
