Repository ethersphere/swarm, pull requests merged in 2019-06, with the labels that each got.

#1420 swarm, cmd: fix migration link, change loglevel severity
  cmd/swarm/db.go
  swarm.go
Labels: bug

#1399 swarm/network/stream: add syncing test
  api/api_test.go
  cmd/swarm-smoke/upload_and_sync.go
  fuse/swarmfs_test.go
  network/stream/common_test.go
  network/stream/syncer_test.go
  storage/filestore.go
Labels: area:network-testing, area:push-sync, network testing

#1465 network: bump proto versions due to change in OfferedHashesMsg
  network/protocol.go
  network/protocol_test.go
  network/stream/stream.go
Labels: ready for review

#1464 cmd/swarm-smoke: add paging to trackChunks
  cmd/swarm-smoke/upload_and_sync.go
Labels: area:network-testing, bug, enhancement, network testing

#1344 simplification of Fetchers
  network/fetcher.go
  network/fetcher_test.go
  network/stream/common_test.go
  network/stream/delivery.go
  network/stream/delivery_test.go
  network/stream/intervals_test.go
  network/stream/messages.go
  network/stream/snapshot_sync_test.go
  network/stream/stream.go
  network/stream/streamer_test.go
  network/stream/syncer.go
  network/timeouts/timeouts.go
  storage/feed/handler.go
  storage/feed/lookup/lookup.go
  storage/feed/testutil.go
  storage/filestore.go
  storage/lnetstore.go
  storage/netstore.go
  storage/netstore_test.go
  storage/request.go
  swarm.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/vendor.json
Labels: ready for review

#1492 simple fetchers
  network/fetcher.go
  network/fetcher_test.go
  network/stream/common_test.go
  network/stream/delivery.go
  network/stream/delivery_test.go
  network/stream/intervals_test.go
  network/stream/messages.go
  network/stream/snapshot_sync_test.go
  network/stream/stream.go
  network/stream/streamer_test.go
  network/stream/syncer.go
  network/timeouts/timeouts.go
  storage/feed/handler.go
  storage/feed/lookup/lookup.go
  storage/feed/testutil.go
  storage/filestore.go
  storage/lnetstore.go
  storage/netstore.go
  storage/netstore_test.go
  storage/request.go
  swarm.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/vendor.json
Labels: ready for review

#1497 network/stream: remove send.offered.hashes trace
  network/stream/peer.go
Labels: ready for review

#1454 docs: add initial stream! protocol specification
  docs/Stream-Protocol-Spec.md
  docs/diagrams/stream-bounded.dia
  docs/diagrams/stream-bounded.png
  docs/diagrams/stream-bounded.svg
  docs/diagrams/stream-handshake.dia
  docs/diagrams/stream-handshake.png
  docs/diagrams/stream-handshake.svg
  docs/diagrams/stream-no-roundtrip.dia
  docs/diagrams/stream-no-roundtrip.png
  docs/diagrams/stream-unbounded.dia
  docs/diagrams/stream-unbounded.png
Labels: documentation, in progress, stream

#1503 network/simulation: Add ExecAdapter capability to swarm simulations
  cmd/swarm-snapshot/create.go
  network/simulation/bucket_test.go
  network/simulation/events_test.go
  network/simulation/example_test.go
  network/simulation/http_test.go
  network/simulation/kademlia_test.go
  network/simulation/node_test.go
  network/simulation/service_test.go
  network/simulation/simulation.go
  network/simulation/simulation_test.go
  network/stream/intervals_test.go
  network/stream/peer_test.go
  network/stream/snapshot_retrieval_test.go
  network/stream/snapshot_sync_test.go
  network/stream/streamer_test.go
  network/stream/syncer_test.go
  network_test.go
  pss/prox_test.go
Labels: enhancement, ready for another review, simulations
