Repository ethersphere/swarm, pull requests merged in 2019-07, with the labels that each got.

#1530 network/bitvector: Multibit set/unset + string rep
  network/bitvector/bitvector.go
  network/bitvector/bitvector_test.go
  network/stream/messages.go
Labels: enhancement, ready for review

#1536 cmd/swarm: use only one function to parse flags
  cmd/swarm/config.go
Labels: ready for review

#1531 cmd/swarm: make bzzaccount flag optional and add bzzkeyhex flag
  Dockerfile
  Dockerfile.alltools
  README.md
  cmd/swarm/access.go
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/download.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  docker/run.sh
Labels: ready for review

#1537 swarm: fix bzz_info.port when using dynamic port allocation
  swarm.go
Labels: ready for review

#1500 network/newstream: new stream! protocol base implementation
  docs/Stream-Protocol-Spec.md
  network/newstream/common_test.go
  network/newstream/peer.go
  network/newstream/stream.go
  network/newstream/wire.go
Labels: area:stability, enhancement

#1534 api, network: count chunk deliveries per peer
  api/inspector.go
  network/stream/delivery.go
Labels: ready for review

#1539 Cheques protocol
  api/config.go
  api/config_test.go
  cmd/swarm/config_test.go
  cmd/swarm/run_test.go
  contracts/chequebook/cheque.go
  contracts/swap/contract/code.go
  contracts/swap/contract/simpleswap.go
  contracts/swap/swap.go
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  swarm.go
  swarm_test.go
Labels: in progress, incentives

#1541 Swap thresholds
  network/stream/constants.go
  network/stream/stream.go
  p2p/protocols/accounting.go
  swap/defaults.go
  swap/peer.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
Labels: incentives

#1557 cmd/swarm: allow using a network interface by name for nat purposes
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
Labels: ready for review

#1578 swarm-smoke: fix check max prox hosts for pull/push sync modes
  cmd/swarm-smoke/main.go
  cmd/swarm-smoke/upload_and_sync.go
  cmd/swarm-smoke/util.go
Labels: ready for review

#1577 contracts, services: removed legacy swap code
  contracts/chequebook/api.go
  contracts/chequebook/cheque.go
  contracts/chequebook/cheque_test.go
  contracts/chequebook/contract/chequebook.go
  contracts/chequebook/contract/chequebook.sol
  contracts/chequebook/contract/code.go
  contracts/chequebook/contract/mortal.sol
  contracts/chequebook/contract/owned.sol
  contracts/chequebook/gencode.go
  services/swap/swap.go
  services/swap/swap/swap.go
  services/swap/swap/swap_test.go
Labels: incentives

#1573 swap: contract integration test with simulated backend
  swap/swap_test.go
Labels: incentives

#1582 client: add bzz client, update smoke tests
  api/inspector.go
  client/bzz.go
  cmd/swarm-smoke/upload_and_sync.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/vendor.json
Labels: ready for review

#1586 network: structured output for kademlia table
  api/inspector.go
  network/kademlia.go
Labels: ready for review

#1587 swap: Incentives prices
  network/discovery_test.go
  network/stream/constants.go
  network/stream/stream.go
  p2p/protocols/accounting.go
  swap/defaults.go
  swap/oracle.go
  swap/peer.go
  swap/prices.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  testutil/dummy.go
Labels: incentives

#1589 network/retrieve: add bzz-retrieve protocol
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/retrieval/wire.go
  network/simulation/bucket.go
  network/simulation/simulation.go
  testutil/node.go
Labels: enhancement, priority, ready for review, stream

#1595 swarm, state, swap/swap: query peer balances
  state/dbstore.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives, ready for review

#1590 swap: load and save received cheques, verify amount and serial are higher
  swap/peer.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1606 swarm, swap: SWAP network whitelist
  swap/defaults.go
  swarm.go
  swarm_test.go
Labels: incentives, ready for review

#1611 swap: added threshold trigger tests
  swap/protocol_test.go
  swap/swap.go
Labels: incentives

#1607 swap: move functions for encoding, signing cheques away from Swap object
  swap/cheque.go
  swap/peer.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1612 swap: add cashChequeBeneficiary
  contracts/swap/swap.go
  swap/peer.go
  swap/swap_test.go
Labels: incentives

#1576 add --disable-auto-connect flag
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  network/hive.go
  swarm.go
Labels: ready for review

#1580 pss: instrumentation and refactor
  api/config.go
  pss/client/client_test.go
  pss/forwarding_test.go
  pss/keystore.go
  pss/notify/notify_test.go
  pss/prox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/types.go
  swarm.go
Labels: ready for another review

#1614 api, chunk: rename Tag.New to Tag.Create
  api/api_test.go
  api/http/middleware.go
  chunk/tag_test.go
  chunk/tags.go
  chunk/tags_test.go
  network_test.go
  swarm_test.go
Labels: ready for review

#1616 simulation: retry if we hit a collision on tcp/udp ports
  simulation/docker.go
  simulation/exec.go
  simulation/simulation.go
Labels: ready for review

#1610 swarm, swap, state: store balances and cheques keys bugfix
  state/dbstore.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives, ready for review

#1625 swap: fix circular import and linter errors
  contracts/swap/swap.go
  network/discovery_test.go
  p2p/protocols/accounting.go
  swap/peer.go
  swap/prices.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  testutil/dummy.go
Labels: incentives
