Repository ethersphere/swarm, pull requests merged in 2019-04, with the labels that each got.

#1330 swarm/chunk, swarm/storage: adjust Store.Put interface to return boolean on chunk exists
  swarm/chunk/chunk.go
  swarm/network/stream/common_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/storage/common_test.go
  swarm/storage/feed/handler_test.go
  swarm/storage/hasherstore.go
  swarm/storage/localstore/export.go
  swarm/storage/localstore/export_test.go
  swarm/storage/localstore/gc_test.go
  swarm/storage/localstore/index_test.go
  swarm/storage/localstore/localstore_test.go
  swarm/storage/localstore/mode_get_test.go
  swarm/storage/localstore/mode_has_test.go
  swarm/storage/localstore/mode_put.go
  swarm/storage/localstore/mode_put_test.go
  swarm/storage/localstore/mode_set_test.go
  swarm/storage/localstore/retrieval_index_test.go
  swarm/storage/localstore/subscription_pull_test.go
  swarm/storage/localstore/subscription_push_test.go
  swarm/storage/netstore.go
  swarm/storage/netstore_test.go
  swarm/storage/types.go
Labels: area:push-sync, ready for review

#1297 cmd/swarm: new localstore database migration
  cmd/swarm/db.go
  cmd/swarm/export_test.go
  cmd/swarm/flags.go
  cmd/swarm/testdata/datastore_fixture.go
  swarm/api/manifest.go
  swarm/storage/localstore/export.go
  swarm/storage/localstore/export_test.go
  swarm/storage/localstore/localstore.go
  swarm/storage/localstore/schema.go
  swarm/swarm.go
Labels: area:db-rewrite, ready for review

#1337 cmd/swarm/swarm-smoke: improve smoke tests
  cmd/swarm/swarm-smoke/feed_upload_and_sync.go
  cmd/swarm/swarm-smoke/main.go
  cmd/swarm/swarm-smoke/sliding_window.go
  cmd/swarm/swarm-smoke/upload_and_sync.go
  cmd/swarm/swarm-smoke/upload_speed.go
  cmd/swarm/swarm-smoke/util.go
  swarm/api/inspector.go
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/stream/delivery.go
Labels: ready for review

#1339 swarm/network: remove dead code
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  p2p/testing/peerpool.go
  swarm/network/hive.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/lightnode_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/snapshot_retrieval_test.go
  swarm/network/stream/snapshot_sync_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/streamer_test.go
  swarm/network/stream/syncer_test.go
  swarm/swarm.go
Labels: ready for review

#1342 swarm/network: remove FetchStore and SyncChunkStore in favor of NetStore
  swarm/chunk/chunk.go
  swarm/network/stream/delivery.go
  swarm/network/stream/intervals_test.go
  swarm/network/stream/syncer.go
Labels: ready for review

#1351 Swarm rather stable: fix data races in TestInitialPeersMsg test:
  p2p/testing/protocoltester.go
  swarm/network/discovery_test.go
  swarm/network/hive.go
  swarm/network/kademlia.go
  swarm/network/protocol_test.go
Labels: ready for review

#1349 Swarm rather stable: LocalStore metrics
  swarm/chunk/chunk.go
  swarm/shed/db.go
  swarm/storage/localstore/gc.go
  swarm/storage/localstore/localstore.go
  swarm/storage/localstore/mode_get.go
  swarm/storage/localstore/mode_has.go
  swarm/storage/localstore/mode_put.go
  swarm/storage/localstore/mode_set.go
  swarm/storage/localstore/subscription_pull.go
  swarm/storage/localstore/subscription_push.go
Labels: ready for review

#1346 p2p/protocols, swarm/network: fix p2p resource leak
  p2p/protocols/protocol_test.go
  swarm/network/hive_test.go
  swarm/network/protocol_test.go
  swarm/network/stream/common_test.go
Labels: area:network-testing, network testing, ready for review

#1353 cmd/swarm-smoke: check if chunks are at most prox host
  cmd/swarm/swarm-smoke/upload_and_sync.go
Labels: ready for review

#1358 swarm/network: measure how many chunks a node delivers
  swarm/network/stream/peer.go
Labels: ready for review

#1341 swarm/chunk: add tags
  swarm/chunk/chunk.go
  swarm/chunk/tag.go
  swarm/chunk/tag_test.go
  swarm/chunk/tags.go
  swarm/sctx/sctx.go
Labels: area:push-sync

#1336 Swarm rather stable: update syncing
  swarm/network/kademlia.go
  swarm/network/kademlia_test.go
  swarm/network/stream/delivery.go
  swarm/network/stream/delivery_test.go
  swarm/network/stream/messages.go
  swarm/network/stream/peer.go
  swarm/network/stream/peer_test.go
  swarm/network/stream/stream.go
  swarm/network/stream/streamer_test.go
  swarm/network/stream/syncer.go
Labels: ready for review
