Repository ethersphere/swarm, pull requests merged in 2019-08, with the labels that each got.

#1628 Incentives API
  swap/protocol.go
  swarm.go
Labels: incentives

#1629 Balance rework (iterate through state store)
  state/dbstore.go
  state/dbstore_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1630 swap: log-levels
  swap/peer.go
  swap/swap.go
Labels: incentives, ready for review

#1645 swap: fixed log messages, renamed stateStore, resetBalance returns err
  swap/peer.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1637 removed TODOs which probably should not be fixed before merge
  contracts/swap/swap.go
  swap/defaults.go
  swap/oracle.go
  swap/peer.go
  swap/protocol_test.go
  swap/swap.go
  swap/types.go
Labels: incentives, ready for review

#1509 Pinning content
  api/api.go
  api/client/client.go
  api/client/client_test.go
  api/http/response_test.go
  api/http/server.go
  api/http/server_test.go
  api/http/test_server.go
  api/manifest.go
  chunk/chunk.go
  cmd/swarm-smoke/upload_and_sync.go
  cmd/swarm-smoke/util.go
  cmd/swarm/access.go
  cmd/swarm/access_test.go
  cmd/swarm/explore.go
  cmd/swarm/feeds_test.go
  cmd/swarm/flags.go
  cmd/swarm/hash.go
  cmd/swarm/manifest.go
  cmd/swarm/manifest_test.go
  cmd/swarm/run_test.go
  cmd/swarm/upload.go
  network/retrieval/retrieve_test.go
  network/stream/common_test.go
  network/stream/delivery.go
  shed/example_store_test.go
  shed/index.go
  state/dbstore.go
  storage/feed/handler.go
  storage/filestore.go
  storage/filestore_test.go
  storage/localstore/export.go
  storage/localstore/gc.go
  storage/localstore/gc_test.go
  storage/localstore/localstore.go
  storage/localstore/mode_get.go
  storage/localstore/mode_set.go
  storage/pin/pin.go
  storage/pin/pin_test.go
  swarm.go
Labels: ready for review

#1659 swap: refactor message handlers to be on
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1664 swarm, swap: extend swap `Stop` function
  swap/protocol.go
  swap/swap.go
  swarm.go
Labels: incentives

#1661 Enable golangci-lint and fix reported errors
  .golangci.yml
  api/api_test.go
  api/http/middleware.go
  api/http/server.go
  api/http/server_test.go
  build/ci.go
  cmd/swarm-smoke/util.go
  cmd/swarm-snapshot/create_test.go
  cmd/swarm/access_test.go
  cmd/swarm/export_test.go
  cmd/swarm/manifest_test.go
  cmd/swarm/run_test.go
  cmd/swarm/upload_test.go
  contracts/chequebook/cheque.go
  internal/build/env.go
  network/network.go
  network/newstream/peer.go
  network/newstream/wire.go
  network/retrieval/retrieve_test.go
  network/simulations/discovery/discovery_test.go
  network/stream/delivery_test.go
  network/stream/peer.go
  p2p/protocols/protocol.go
  pot/address.go
  pot/pot.go
  pot/pot_test.go
  pss/prox_test.go
  pss/pss_test.go
  storage/feed/lookup/lookup_test.go
  storage/localstore/subscription_pull_test.go
Labels: ready for review

#1647 p2p/testing: reinstate pkg within swarm
  network/discovery_test.go
  network/hive_test.go
  network/protocol_test.go
  network/stream/common_test.go
  network/stream/delivery_test.go
  network/stream/lightnode_test.go
  network/stream/streamer_test.go
  p2p/protocols/protocol_test.go
  p2p/testing/peerpool.go
  p2p/testing/protocolsession.go
  p2p/testing/protocoltester.go
  vendor/modules.txt
Labels: ready for review, test

#1667 README.md: Update Vendored Dependencies section
  README.md
Labels: area:docs

#1621 pot: Add Distance methods with tests
  network/discovery.go
  pot/address.go
  pot/address_test.go
Labels: enhancement, merge-imminent, pot

#1658 HTTP API support for pinning contents
  api/client/client_test.go
  api/http/server.go
  api/http/server_test.go
  api/http/test_server.go
  api/uri.go
  cmd/swarm/feeds_test.go
  cmd/swarm/run_test.go
  storage/pin/pin.go
  storage/pin/pin_test.go
  swarm.go
Labels: http interface, pinning, ready for review

#1670 storage: fix LazyChunkReader.join potential deadlock
  storage/chunker.go
Labels: bug, chunker rewrite, ready for review

#1673 api/http: remove unnecessary conversion
  api/http/server_test.go
Labels: ready for review

#1648 p2p/protocols, p2p/testing; conditional propagation of context
  p2p/protocols/context.go
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  p2p/testing/protocoltester.go
Labels: monitoring, ready for review

#1619 network: Add adaptive capabilities message
  network/adaptive.go
  network/adaptive_test.go
  network/protocol.go
  network/protocol_test.go
Labels: enhancement, merge-imminent

#1677 swap: createCheque refactor
  swap/cheque.go
  swap/swap.go
Labels: incentives

#1678 swap: cheque functions refactor
  swap/swap.go
  swap/swap_test.go
Labels: incentives

#1672 pss: Use distance metric for test success
  pss/prox_test.go
Labels: enhancement, pss, ready for review

#1679 storage: fix pyramid chunker and hasherstore possible deadlocks
  storage/hasherstore.go
  storage/pyramid.go
Labels: bug

#1681 chunk, storage: chunk.Store multiple chunk Put
  chunk/chunk.go
  network/stream/common_test.go
  storage/common_test.go
  storage/hasherstore.go
  storage/localstore/gc_test.go
  storage/localstore/localstore_test.go
  storage/localstore/mode_put.go
  storage/localstore/mode_put_test.go
  storage/netstore.go
  storage/types.go
Labels: ready for review

#1649 api, chunk: progress bar support
  api/client/client.go
  api/http/middleware.go
  api/http/server.go
  api/http/server_test.go
  api/uri.go
  chunk/tag.go
  chunk/tag_test.go
  chunk/tags.go
  chunk/tags_test.go
  state/dbstore.go
  storage/pin/pin.go
  swarm.go
  testutil/tag.go
Labels: http interface, ready for review, tags

#1691 chunk, shed, storage: chunk.Store GetMulti method
  chunk/chunk.go
  network/stream/common_test.go
  shed/index.go
  shed/index_test.go
  storage/common_test.go
  storage/localstore/localstore_test.go
  storage/localstore/mode_get.go
  storage/localstore/mode_get_multi.go
  storage/localstore/mode_get_multi_test.go
  storage/localstore/mode_get_test.go
  storage/types.go
Labels: ready for review

#1684 chunk, storage: storage with multi chunk Set method
  chunk/chunk.go
  storage/common_test.go
  storage/localstore/localstore_test.go
  storage/localstore/mode_put_test.go
  storage/localstore/mode_set.go
  storage/localstore/mode_set_test.go
  storage/types.go
Labels: ready for review

#1571 bzzeth: initial support for bzz-eth protocol
  bzzeth/bzzeth.go
  bzzeth/bzzeth_test.go
  bzzeth/peer.go
  bzzeth/wire.go
  swarm.go
Labels: blockchain-on-swarm, ready for review

#1700 storage: fix hasherstore seen panic
  storage/hasherstore.go
Labels: bug

#1682 pss: Port tests to `network/simulation`
  pss/handshake_test.go
  pss/protocol_test.go
  pss/pss_test.go
Labels: enhancement, pss, ready for review, simulations

#1702 pss: fixed flaky test TestForwardBasic
  pss/forwarding_test.go
Labels: flaky test, pss, ready for review

#1675 network: Add API for Capabilities
  network/capability/api.go
  network/capability/api_test.go
  network/capability/capability.go
  network/capability/capability_test.go
  network/protocol.go
  network/protocol_test.go
Labels: enhancement, ready for another review

#1709 cmd/swarm-snapshot: if 2 nodes to create snapshot use connectChain
  cmd/swarm-snapshot/create.go
Labels: area:network-testing, ready for review
