Repository ethersphere/swarm, pull requests merged in 2019-09, with the labels that each got.

#1695 pss: Improve pressure backstop queue handling - no mutex
  pss/forwarding_test.go
  pss/pss.go
  pss/pss_test.go
Labels: enhancement, pss, ready for review

#1698 pss: Modularize crypto and remove Whisper. Step 1 - isolate whisper code
  pss/api.go
  pss/client/client_test.go
  pss/crypto.go
  pss/forwarding_test.go
  pss/handshake.go
  pss/keystore.go
  pss/message.go
  pss/notify/notify.go
  pss/notify/notify_test.go
  pss/prox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/types.go
Labels: enhancement, pss, ready for another review

#1683 swap, contracts, vendor: move to waiver-free simplestswap
  contracts/swap/contract/code.go
  contracts/swap/swap.go
  go.mod
  go.sum
  swap/cheque.go
  swap/config.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-0/simpleswap/code.go
  vendor/github.com/ethersphere/go-sw3/contracts-v0-1-0/simpleswap/simpleswap.go
  vendor/modules.txt
Labels: incentives

#1721 swap: fix TestHandshake and TestEmitCheque
  swap/protocol_test.go
Labels: incentives

#1727 network/newstream: encode sync stream keys with base 36
  network/newstream/cursors_test.go
  network/newstream/sync_provider.go
Labels: ready for review

#1718 swarm, swap: pass chequebook address at start-up
  swap/protocol.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives, ready for review

#1733 Incentives rpc test
  swap/protocol_test.go
Labels: incentives, ready for review

#1740 network: terminate Hive connect goroutine on Stop
  network/hive.go
Labels: ready for review

#1725 swap: refactor lastReceivedCheque, lastSentCheque, balances to peer
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for another review, ready for review

#1710 Go 1.13 support
  .travis.yml
  Dockerfile
  Dockerfile.alltools
  api/api_test.go
  api/client/client_test.go
  api/http/server_test.go
  appveyor.yml
  bzzeth/bzzeth_test.go
  chunk/testing/tag.go
  cmd/swarm/run_test.go
  cmd/swarm/upload_test.go
  fuse/swarmfs_test.go
  network/networkid_test.go
  network/newstream/common_test.go
  network/protocol_test.go
  network/retrieval/retrieve_test.go
  network/simulation/simulation_test.go
  network/simulations/discovery/discovery_test.go
  network/simulations/overlay.go
  network/stream/common_test.go
  network/stream/snapshot_retrieval_test.go
  network/stream/snapshot_sync_test.go
  network/stream/streamer_test.go
  network_test.go
  p2p/protocols/accounting_simulation_test.go
  pss/client/client_test.go
  pss/notify/notify_test.go
  pss/prox_test.go
  pss/pss_test.go
  simulation/examples/cluster/cluster_test.go
  storage/common_test.go
  storage/feed/handler_test.go
  swap/swap_test.go
  swarm_test.go
  testutil/init.go
  testutil/init_go1.13.go
  testutil/node.go
Labels: ready for review, test

#1743 swap: fix rpc test to use peer balance
  swap/protocol_test.go
Labels: incentives, ready for review

#1748 contracts/swap, swap: refactor contractAddress, remove backend as inputParam, function order in contracts/swap
  contracts/swap/swap.go
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#1762 network: fix data race in simulation.NewBzzInProc
  network/retrieval/retrieve_test.go
  network/simulation/simulation.go
  network/stream/v2/common_test.go
Labels: ready for review

#1758 network/retrieval: add balances to the retrieval protocol
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/stream/v2/common_test.go
  swarm.go
Labels: in progress

#1734 pss: Refactor. Step 1. Refactor PssMsg
  pss/ARCHITECTURE.md
  pss/api.go
  pss/client/client.go
  pss/doc.go
  pss/forwarding_test.go
  pss/handshake.go
  pss/keystore.go
  pss/message/flags.go
  pss/message/flags_test.go
  pss/message/message.go
  pss/message/message_test.go
  pss/message/topic.go
  pss/message/topic_test.go
  pss/notify/notify.go
  pss/notify/notify_test.go
  pss/protocol.go
  pss/prox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/types.go
  swarm.go
Labels: pss, ready for review

#1765 network/retrieval: fix Price method reflect call
  network/retrieval/retrieve.go
Labels: ready for review

#1770 stream: fix missing pointer in Send call
  network/stream/v2/sync_provider.go
Labels: bug, ready for review, stream

#1760 network/stream/v2: more resilient TestNodesExchangeCorrectBinIndexes
  network/stream/v2/cursors_test.go
Labels: ready for review

#1729 cmd/swarm, swarm, swap, api: configurable payment/disconnect thresholds
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  swap/config.go
  swap/honeyOracle.go
  swap/peer.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
  swarm_test.go
Labels: incentives, ready for review

#1742 pss: Refactor. Step 2. Refactor forward cache
  go.mod
  go.sum
  pss/internal/ticker/ticker.go
  pss/internal/ticker/ticker_test.go
  pss/internal/ttlset/ttlset.go
  pss/internal/ttlset/ttlset_test.go
  pss/pss.go
  pss/pss_test.go
  vendor/github.com/tilinna/clock/.gitignore
  vendor/github.com/tilinna/clock/.travis.yml
  vendor/github.com/tilinna/clock/LICENSE
  vendor/github.com/tilinna/clock/README.md
  vendor/github.com/tilinna/clock/clock.go
  vendor/github.com/tilinna/clock/context.go
  vendor/github.com/tilinna/clock/go.mod
  vendor/github.com/tilinna/clock/heap.go
  vendor/github.com/tilinna/clock/mock.go
  vendor/github.com/tilinna/clock/ticker.go
  vendor/github.com/tilinna/clock/timer.go
  vendor/modules.txt
Labels: pss, ready for review

#1775 network: add own address to KademliaInfo
  network/kademlia.go
Labels: ready for review

#1713 network: Add Capabilities to Kademlia database
  cmd/swarm-snapshot/create.go
  cmd/swarm/run_test.go
  network/capability/capability.go
  network/capability/capability_test.go
  network/discovery.go
  network/discovery_test.go
  network/enr.go
  network/hive.go
  network/hive_test.go
  network/kademlia.go
  network/kademlia_test.go
  network/network.go
  network/network_test.go
  network/networkid_test.go
  network/protocol.go
  network/protocol_test.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/simulation/example_test.go
  network/simulation/kademlia_test.go
  network/simulation/node_test.go
  network/simulation/simulation.go
  network/simulations/discovery/discovery_test.go
  network/simulations/overlay.go
  network/stream/v2/common_test.go
  network/stream/v2/cursors_test.go
  network/stream/v2/syncing_test.go
  pot/pot.go
  pss/client/client_test.go
  pss/client/doc.go
  pss/forwarding_test.go
  pss/notify/notify_test.go
  pss/prox_test.go
  pss/pss_test.go
Labels: enhancement, kademlia, light node, ready for another review

#1776 network/stream: more resilient TestNodesCorrectBinsDynamic
  network/stream/v2/cursors_test.go
Labels: ready for review

#1769 swap: fix and rename Peer.getLastSentCumulativePayout
  swap/peer.go
  swap/swap_test.go
Labels: incentives, ready for review

#1778 build: increase golangci-lint deadline
  build/ci.go
Labels: ready for review

#1781 cmd/swamr-smoke: fix waitToPushSynced connection closing
  cmd/swarm-smoke/upload_and_sync.go
Labels: ready for review

#1771 protocols, retrieval: swap-enabled messages implement Price
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  p2p/protocols/accounting.go
  p2p/protocols/accounting_simulation_test.go
  p2p/protocols/accounting_test.go
Labels: incentives, ready for review

#1779 network/stream: handle nil peer in TestNodesExchangeCorrectBinIndexes
  network/stream/v2/cursors_test.go
Labels: ready for review

#1764 network, pss: Capability in pss
  network/discovery_test.go
  network/kademlia.go
  network/networkid_test.go
  network/protocol.go
  pss/pss.go
  swarm.go
Labels: enhancement, kademlia, light node, pss, ready for review

#1761 cmd/swarm: correct bzznetworkid flag description
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
Labels: ready for review

#1784 travis: remove go1.12 job
  .travis.yml
  go.mod
Labels: ready for review

#1787 network: Add capability filtered depth calculation
  network/kademlia.go
  network/kademlia_test.go
Labels: enhancement, kademlia, light node, ready for review

#1754 Swap logger
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  internal/debug/flags.go
  log/log.go
  swap/peer.go
  swap/protocol.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives, ready for another review

#1791 network: Patch crash on pre-capability state store load
  network/hive.go
Labels: bug, ready for review

#1786 network/stream: refactor cursors tests
  network/stream/v2/common_test.go
  network/stream/v2/cursors_test.go
Labels: ready for review

#1685 bzzeth: Phase 1
  bzzeth/bzzeth.go
  bzzeth/bzzeth_test.go
  bzzeth/peer.go
  bzzeth/wire.go
  swarm.go
Labels: blockchain-on-swarm, ready for review

#1815 bzzeth: correct the order of cleanup steps in newTestNetworkStore
  bzzeth/bzzeth_test.go
Labels: ready for review

#1782 pushsync with async pss
  api/api_test.go
  api/client/client_test.go
  api/config.go
  api/http/server.go
  api/http/server_test.go
  api/inspector.go
  chunk/chunk.go
  chunk/tag.go
  chunk/tags.go
  chunk/tags_test.go
  chunk/testing/tag.go
  cmd/swarm-smoke/upload_and_sync.go
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  integration-tests/README.md
  integration-tests/pushsync/.env
  integration-tests/pushsync/deployment.yaml
  integration-tests/pushsync/deployment/private-smoke-a.yaml
  integration-tests/pushsync/deployment/private-swarm.yaml
  integration-tests/pushsync/deployment/version.yaml
  integration-tests/pushsync/smoke-job.yaml
  network/kademlia.go
  network/retrieval/retrieve_test.go
  network/simulation/simulation.go
  network/stream/v2/cursors_test.go
  network/stream/v2/snapshot_sync_test.go
  network/stream/v2/syncing_test.go
  network_test.go
  pot/address.go
  pot/address_test.go
  pss/pss.go
  pss/pss_test.go
  pss/pubsub.go
  pushsync/protocol.go
  pushsync/protocol_test.go
  pushsync/pusher.go
  pushsync/pusher_test.go
  pushsync/simulation_test.go
  pushsync/storer.go
  shed/index.go
  storage/hasherstore.go
  storage/localstore/localstore.go
  storage/localstore/subscription_push.go
  storage/netstore.go
  swarm.go
  swarm_test.go
Labels: ready for review

#1789 swap: prompt user for initial deposit amount
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
  swarm_test.go
Labels: incentives

#1816 build: add -trimpath build/install option
  build/ci.go
Labels: ready for review

#1818 bzzeth: fix TestBzzBzzHandshakeWithMessage
  bzzeth/bzzeth_test.go
Labels: ready for review, test

#1797 swap: chequebook persistence
  contracts/swap/swap.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
  swarm_test.go
Labels: incentives, ready for review

#1826 swap: return the balance in swap.Balance for an unconnected but prior peer
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#1819 pushsync: optimize TestPushsyncSimulation
  chunk/testing/chunk.go
  pushsync/simulation_test.go
  storage/localstore/localstore_test.go
Labels: ready for review, test

#1830 swarm: make pullsync disabled not expose stream protocol
  network/discovery.go
  swarm.go
Labels: bug

#1832 network/stream: skip longrunning simulation due to travis flakes
  network/stream/v2/snapshot_sync_test.go
Labels: flaky test

#1834 network: disable stream spec in bzz if pull sync is not enabled
  network/protocol.go
  swarm.go
Labels: ready for review

#1793 cmd/swarm-smoke: add flag to bail on error
  cmd/swarm-smoke/flags.go
  cmd/swarm-smoke/main.go
  cmd/swarm-smoke/upload_and_sync.go
Labels: enhancement

#1814 cmd/swarm: add cli UI for tag progress on pushsync
  api/client/client.go
  api/client/client_test.go
  cmd/swarm/access_test.go
  cmd/swarm/export_test.go
  cmd/swarm/flags.go
  cmd/swarm/fs_test.go
  cmd/swarm/manifest_test.go
  cmd/swarm/upload.go
  cmd/swarm/upload_test.go
  go.mod
  go.sum
  vendor/github.com/VividCortex/ewma/.gitignore
  vendor/github.com/VividCortex/ewma/LICENSE
  vendor/github.com/VividCortex/ewma/README.md
  vendor/github.com/VividCortex/ewma/ewma.go
  vendor/github.com/vbauerster/mpb/.gitignore
  vendor/github.com/vbauerster/mpb/.travis.yml
  vendor/github.com/vbauerster/mpb/LICENSE
  vendor/github.com/vbauerster/mpb/README.md
  vendor/github.com/vbauerster/mpb/bar.go
  vendor/github.com/vbauerster/mpb/bar_filler.go
  vendor/github.com/vbauerster/mpb/bar_option.go
  vendor/github.com/vbauerster/mpb/cwriter/writer.go
  vendor/github.com/vbauerster/mpb/cwriter/writer_posix.go
  vendor/github.com/vbauerster/mpb/cwriter/writer_windows.go
  vendor/github.com/vbauerster/mpb/decor/counters.go
  vendor/github.com/vbauerster/mpb/decor/decorator.go
  vendor/github.com/vbauerster/mpb/decor/doc.go
  vendor/github.com/vbauerster/mpb/decor/elapsed.go
  vendor/github.com/vbauerster/mpb/decor/eta.go
  vendor/github.com/vbauerster/mpb/decor/moving-average.go
  vendor/github.com/vbauerster/mpb/decor/name.go
  vendor/github.com/vbauerster/mpb/decor/percentage.go
  vendor/github.com/vbauerster/mpb/decor/speed.go
  vendor/github.com/vbauerster/mpb/doc.go
  vendor/github.com/vbauerster/mpb/go.test.sh
  vendor/github.com/vbauerster/mpb/internal/percentage.go
  vendor/github.com/vbauerster/mpb/options.go
  vendor/github.com/vbauerster/mpb/priority_queue.go
  vendor/github.com/vbauerster/mpb/progress.go
  vendor/github.com/vbauerster/mpb/progress_posix.go
  vendor/github.com/vbauerster/mpb/progress_windows.go
  vendor/github.com/vbauerster/mpb/proxyreader.go
  vendor/github.com/vbauerster/mpb/spinner_filler.go
  vendor/modules.txt
Labels: cli, enhancement, ready for review

#1840 pushsync: reduce testcases in simulation because Travis
  pushsync/simulation_test.go
Labels: ready for review
