Repository ethersphere/swarm, pull requests merged in 2020-05, with the labels that each got.

#2166 trigger trojan chunk sending
  chunk/chunk.go
  prod/prod.go
  prod/prod_test.go
  pss/pss_test.go
  pss/testing/pss.go
  storage/netstore.go
  swarm.go
Labels: global pinning, ready for review

#2178 prod, pss, trojan: add Target and Targets types
  prod/prod.go
  prod/prod_test.go
  pss/pss.go
  pss/pss_test.go
  pss/trojan/message.go
  pss/trojan/message_test.go
Labels: global pinning, ready for review

#2179 feed: add handler interface and testutils
  storage/feed/handler.go
  storage/feed/testutil.go
Labels: global pinning, ready for review

#2175 api, cmd, prod, pss, swarm: get publisher and query feed for chunk repair request
  api/api.go
  api/client/client.go
  api/client/client_test.go
  api/http/server.go
  api/manifest.go
  chunk/chunk.go
  cmd/swarm-smoke/util.go
  cmd/swarm/flags.go
  cmd/swarm/upload.go
  prod/prod.go
  prod/prod_test.go
  pss/pss_test.go
  pss/testing/pss.go
  storage/netstore.go
  swarm.go
Labels: global pinning, ready for review

#2185 prod, swarm: enable content recovery requests all nodes
  prod/prod.go
  swarm.go
Labels: bug, global pinning, ready for review

#2188 prod: improve global pinning recovery hook tests
  prod/prod_test.go
Labels: cleanup, global pinning, ready for review, test

#2191 chunk, feed, storage, feed: condition trojan chunk inspection
  chunk/chunk.go
  storage/feed/handler.go
  storage/feed/handler_test.go
  storage/types.go
Labels: global pinning, ready for review
