Repository ethersphere/swarm, pull requests merged in 2020-01, with the labels that each got.

#2064 tracing: fix Setup function
  tracing/tracing.go
Labels: bug, ready for review

#1981 network/retrieval: integrate kademlia load balancing
  network/kademlia_load_balancer_test.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
Labels: enhancement, kademlia, network, ready for review, stability

#2069 swap: make Uint256 value field private and non-pointer
  swap/api.go
  swap/cheque.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  swap/types_test.go
Labels: builds on open PR, incentives, ready for review

#2051 P2p validate accounting
  p2p/protocols/accounting.go
  p2p/protocols/accounting_simulation_test.go
  p2p/protocols/accounting_test.go
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  swap/swap.go
Labels: incentives

#2018 p2p, network, bzzeth: p2p protocol handlers to async
  bzzeth/bzzeth.go
  network/hive.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/stream/common_test.go
  network/stream/stream.go
  network/stream/syncing_test.go
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  pss/outbox/outbox_test.go
Labels: ready for review

#2072 network, storage: fix usage of base logger
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/stream/sync_provider.go
  storage/netstore.go
Labels: bug

#2066 swap: refactor cashout logic to cashout processor
  contracts/swap/swap.go
  swap/cashout.go
  swap/cashout_test.go
  swap/config.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#2074 swap: move shared test helpers to separate file
  swap/cashout_test.go
  swap/common_test.go
  swap/swap_test.go
Labels: incentives, ready for review

#2062 Protocol async errors refactor
  bzzeth/bzzeth.go
  network/protocol_test.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  network/stream/peer.go
  network/stream/stream.go
  p2p/protocols/error.go
  p2p/protocols/protocol.go
  p2p/protocols/protocol_test.go
  pss/pss.go
  pss/pss_test.go
  swap/protocol_test.go
  swap/swap.go
  swap/swap_test.go
Labels: ready for review

#2065 network: Suggest peer by address space gap
  network/README.md
  network/kademlia.go
  network/kademlia_test.go
  network_test.go
  pot/pot.go
  pot/pot_test.go
Labels: ready for review

#2076 swap, uint256: move Uint256 implementation to new swarm/uint256 package
  swap/api.go
  swap/cashout_test.go
  swap/cheque.go
  swap/common_test.go
  swap/peer.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  uint256/uint256.go
  uint256/uint256_test.go
Labels: builds on open PR, incentives, ready for review

#2063 swap, uint256: unify variable types, pt. 1
  swap/api.go
  swap/cashout.go
  swap/cashout_test.go
  swap/cheque.go
  swap/common_test.go
  swap/peer.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swap/types.go
  uint256/uint256.go
  uint256/uint256_test.go
Labels: incentives, ready for another review

#2073 kademlia: use IsSameAs instead of Match for capability index comparison
  network/kademlia.go
  network/kademlia_test.go
Labels: bug, ready for review

#2081 api: do not try to resolve swarm hashes over ens
  api/api.go
  api/api_test.go
Labels: ready for review
