Repository ethersphere/swarm, pull requests merged in 2020-06, with the labels that each got.

#2199 prod: use bzzaccounts as global pinning publishers
  prod/prod.go
  prod/prod_test.go
Labels: global pinning, ready for review

#2200 storage/localstore: Local Pinning fix for pinned chunks
  storage/localstore/localstore_test.go
  storage/localstore/mode_get.go
  storage/localstore/mode_put.go
  storage/localstore/mode_set.go
Labels: bug, localstore

#2197 swarm, main, api: split sync flag into push and pull flags
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/config_test.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  swarm.go
Labels: cli, global pinning, push-sync, ready for review

#2201 chunk, feed, storage, pss: further condition trojan chunk inspection
  chunk/chunk.go
  pss/pss.go
  pss/pss_test.go
  pss/trojan/message.go
  pss/trojan/message_test.go
  storage/feed/handler.go
  storage/feed/handler_test.go
  storage/types.go
Labels: global pinning, ready for review

#2203 localstore: remove putToGCCheck calls in localstore
  storage/localstore/mode_put.go
  storage/localstore/mode_put_test.go
Labels: bug, global pinning, localstore, ready for review

#2202 api,client,http,main,prod,storage: Add query param for publisher and solve flooding in recovery
  api/api.go
  api/client/client.go
  api/client/client_test.go
  api/http/server.go
  api/manifest.go
  cmd/swarm-smoke/util.go
  cmd/swarm/download.go
  cmd/swarm/flags.go
  cmd/swarm/list.go
  cmd/swarm/upload.go
  prod/prod.go
  storage/netstore.go
Labels: global pinning, ready for another review, ready for review

#2208 chunk, prod, storage, pss: add global pinning logs
  chunk/chunk.go
  prod/prod.go
  pss/pss.go
  storage/netstore.go
Labels: global pinning, ready for review
