Repository ethersphere/swarm, pull requests merged in 2020-04, with the labels that each got.

#2149 pss: add newpss
  pss/ARCHITECTURE.md
  pss/README.md
  pss/api.go
  pss/client/client.go
  pss/client/client_test.go
  pss/client/doc.go
  pss/crypto/crypto.go
  pss/doc.go
  pss/forwarding_test.go
  pss/handshake.go
  pss/handshake_none.go
  pss/handshake_test.go
  pss/internal/ticker/ticker.go
  pss/internal/ticker/ticker_test.go
  pss/internal/ttlset/ttlset.go
  pss/internal/ttlset/ttlset_test.go
  pss/keystore.go
  pss/message/flags.go
  pss/message/flags_test.go
  pss/message/message.go
  pss/message/message_test.go
  pss/message/topic.go
  pss/message/topic_test.go
  pss/notify/notify.go
  pss/notify/notify_test.go
  pss/outbox/message.go
  pss/outbox/mock.go
  pss/outbox/outbox.go
  pss/outbox/outbox_test.go
  pss/outbox/outbox_whitebox_test.go
  pss/ping.go
  pss/protocol.go
  pss/protocol_none.go
  pss/protocol_test.go
  pss/prox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/pubsub.go
  pss/testdata/snapshot_128.json
  pss/testdata/snapshot_16.json
  pss/testdata/snapshot_2.json
  pss/testdata/snapshot_256.json
  pss/testdata/snapshot_3.json
  pss/testdata/snapshot_32.json
  pss/testdata/snapshot_4.json
  pss/testdata/snapshot_64.json
  pss/testdata/snapshot_8.json
  pss/types.go
  pss/writeup.md
Labels: global pinning, ready for review

#2152 pss: remove pss package for global pinning
  pss/ARCHITECTURE.md
  pss/README.md
  pss/api.go
  pss/client/client.go
  pss/client/client_test.go
  pss/client/doc.go
  pss/crypto/crypto.go
  pss/doc.go
  pss/forwarding_test.go
  pss/handshake.go
  pss/handshake_none.go
  pss/handshake_test.go
  pss/internal/ticker/ticker.go
  pss/internal/ticker/ticker_test.go
  pss/internal/ttlset/ttlset.go
  pss/internal/ttlset/ttlset_test.go
  pss/keystore.go
  pss/message/flags.go
  pss/message/flags_test.go
  pss/message/message.go
  pss/message/message_test.go
  pss/message/topic.go
  pss/message/topic_test.go
  pss/notify/notify.go
  pss/notify/notify_test.go
  pss/outbox/message.go
  pss/outbox/mock.go
  pss/outbox/outbox.go
  pss/outbox/outbox_test.go
  pss/outbox/outbox_whitebox_test.go
  pss/ping.go
  pss/protocol.go
  pss/protocol_none.go
  pss/protocol_test.go
  pss/prox_test.go
  pss/pss.go
  pss/pss_test.go
  pss/pubsub.go
  pss/testdata/snapshot_128.json
  pss/testdata/snapshot_16.json
  pss/testdata/snapshot_2.json
  pss/testdata/snapshot_256.json
  pss/testdata/snapshot_3.json
  pss/testdata/snapshot_32.json
  pss/testdata/snapshot_4.json
  pss/testdata/snapshot_64.json
  pss/testdata/snapshot_8.json
  pss/types.go
  pss/writeup.md
Labels: cleanup, global pinning

#2148 pss: add trojan chunks
  pss/trojan/message.go
  pss/trojan/message_test.go
Labels: global pinning, ready for review

#2150 pss: add new pss
  pss/pss.go
  pss/pss_test.go
Labels: global pinning, in progress

#2158 trojan, pss, swarm, api, main, localstore: add store hook for trojan messages
  api/config.go
  chunk/chunk.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  pss/pss.go
  pss/pss_test.go
  pss/trojan/message.go
  pss/trojan/message_test.go
  swarm.go
  swarm_test.go
Labels: global pinning, ready for review

#2164 chunk/testing: fixed Sent conditional in CheckTag
  api/client/client_test.go
  chunk/testing/tag.go
  storage/localstore/mode_set_test.go
Labels: bug

#2159 pss: add pss monitoring capabilities
  build/ci.go
  pss/pss.go
  pss/pss_test.go
  swarm.go
Labels: global pinning, in progress

#2165 chunk, localstore, trojan, swarm: repair globally pinned content
  chunk/chunk.go
  pss/trojan/message.go
  storage/localstore/mode_set.go
  storage/localstore/mode_set_test.go
  swarm.go
Labels: global pinning, ready for review
