Repository ethersphere/swarm, pull requests merged in 2020-02, with the labels that each got.

#2088 state, swap: add batch support to state store
  state/dbstore.go
  state/dbstore_test.go
  swap/swap.go
Labels: incentives, ready for review

#2090 api/http/langos: fix TestHTTPMultipleRangeResponse test
  api/http/langos/http_test.go
Labels: ready for review

#1983 swap: prevent debt cheques
  swap/config.go
  swap/peer.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for another review

#2091 contract/ens: use new ens contract address
  api/config.go
  contracts/ens/ens.go
  swarm.go
Labels: ready for review

#2095 stream: fix stream not wanted bug
  network/stream/stream.go
Labels: bug, ready for review

#2096 stream: remove semaphor hack
  network/stream/cursors_test.go
  network/stream/sync_provider.go
Labels: cleanup

#2021 bmt, param: Introduce SectionHasher interface, implement in bmt
  bmt/bmt.go
  bmt/bmt_bench_test.go
  bmt/bmt_test.go
  file/types.go
  storage/chunker_test.go
  storage/common_test.go
  storage/hasherstore.go
  storage/swarmhasher.go
  storage/types.go
Labels: enhancement, hashing, ready for another review

#2094 version: 0.5.6-stable
  CHANGELOG.md
  version/version.go
Labels: ready for review

#2100 bmt: fix data races in Hasher
  bmt/bmt.go
Labels: ready for review

#2092 contract, swap: refactor backend to commit on sendTransaction
  contracts/swap/factory.go
  contracts/swap/swap.go
  swap/cashout.go
  swap/cashout_test.go
  swap/chain/backend.go
  swap/chain/mock/testbackend.go
  swap/common_test.go
  swap/simulations_test.go
  swap/swap.go
Labels: incentives, ready for review

#2105 http: remove spamming logline
  api/http/server.go
Labels: cleanup

#2104 stream: make empty wanted hashes more explicit
  network/stream/stream.go
Labels: cleanup

#2103 retrieval: fix memory leak
  network/kademlia.go
  network/retrieval/peer.go
  network/retrieval/retrieve.go
  network/retrieval/retrieve_test.go
  storage/feed/testutil.go
  storage/netstore.go
Labels: bug

#2106 swap: fix various data races
  contracts/swap/swap.go
  swap/api.go
  swap/common_test.go
  swap/protocol_test.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
Labels: incentives, ready for review

#2112 p2p/protocols: remove peer accounting lock
  p2p/protocols/protocol.go
Labels: incentives, ready for review

#2107 stream: eliminate overlapping requests on the same stream
  network/stream/peer.go
  network/stream/stream.go
Labels: bug

#2099 file, testutil: Add reference file hasher
  file/hasher/common_test.go
  file/hasher/hasher.go
  file/hasher/hasher_test.go
  file/hasher/param.go
  file/hasher/reference.go
  file/hasher/reference_test.go
  file/hasher/util.go
  file/hasher/util_test.go
  testutil/data.go
Labels: enhancement, hashing, ready for another review

#2115 file: Move AsyncHasher to prepare for avoiding circular dep later
  file/bmt/async.go
  file/bmt/async_test.go
Labels: cleanup, hashing, ready for review
