Repository ethersphere/swarm, pull requests merged in 2020-03, with the labels that each got.

#2119 cmd/swarm,api,swap: Swap logger actions updated
  api/config.go
  cmd/swarm/config.go
  cmd/swarm/flags.go
  cmd/swarm/main.go
  swap/cashout.go
  swap/cashout_test.go
  swap/common_test.go
  swap/log.go
  swap/peer.go
  swap/protocol.go
  swap/simulations_test.go
  swap/swap.go
  swap/swap_test.go
  swarm.go
Labels: incentives

#2136 cmd/swarm,pss,swap: fixed linter errors S1038/S1039
  cmd/swarm/config.go
  cmd/swarm/download.go
  cmd/swarm/main.go
  cmd/swarm/upload_test.go
  pss/api.go
  swap/swap.go
Labels: priority

#2140 p2p, retrieval, storage: reduce logging
  network/retrieval/retrieve.go
  p2p/protocols/protocol.go
  storage/netstore.go
Labels: cleanup

#2144 all: Upgrade golang version to v1.14
  .travis.yml
  Dockerfile
  Dockerfile.alltools
  README.md
  appveyor.yml
Labels: ready for review

#2139 all: change metric names delimiter . to / (#2138)
  README.md
  api/api.go
  api/client/client.go
  api/http/middleware.go
  api/http/response.go
  api/http/server.go
  cmd/swarm-smoke-pss/main.go
  cmd/swarm-smoke-pss/pss.go
  cmd/swarm-smoke-pss/util.go
  cmd/swarm-smoke/feed_upload_and_sync.go
  cmd/swarm-smoke/main.go
  cmd/swarm-smoke/sliding_window.go
  cmd/swarm-smoke/upload_and_sync.go
  cmd/swarm-smoke/upload_speed.go
  cmd/swarm-smoke/util.go
  metrics/flags.go
  metrics/influxdb/influxdb.go
  metrics/runtime.go
  metrics/runtime_cgo.go
  metrics/runtime_gccpufraction.go
  metrics/runtime_no_cgo.go
  metrics/runtime_no_gccpufraction.go
  network/kademlia.go
  network/priorityqueue/priorityqueue.go
  network/retrieval/retrieve.go
  network/stream/stream.go
  network/stream/sync_provider.go
  p2p/protocols/accounting.go
  p2p/protocols/protocol.go
  p2p/protocols/reporter.go
  pss/keystore.go
  pss/outbox/outbox.go
  pss/pss.go
  pss/pubsub.go
  pushsync/pusher.go
  shed/db.go
  storage/chunker.go
  storage/localstore/gc.go
  storage/localstore/localstore.go
  storage/localstore/mode_get.go
  storage/localstore/mode_get_multi.go
  storage/localstore/mode_has.go
  storage/localstore/mode_put.go
  storage/localstore/mode_set.go
  storage/localstore/subscription_pull.go
  storage/localstore/subscription_push.go
  storage/netstore.go
  swap/cashout.go
  swap/peer.go
  swap/simulations_test.go
  swap/swap.go
  swarm.go
Labels: ready for review
